/** Banco oficial do Quiz dos Profetas Menores. 60 questões: 5 por profeta. */
const uuid=(n)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
export const PROPHETS = [
  {
    "id": "oseias",
    "name": "Oséias"
  },
  {
    "id": "joel",
    "name": "Joel"
  },
  {
    "id": "amos",
    "name": "Amós"
  },
  {
    "id": "obadias",
    "name": "Obadias"
  },
  {
    "id": "jonas",
    "name": "Jonas"
  },
  {
    "id": "miqueias",
    "name": "Miquéias"
  },
  {
    "id": "naum",
    "name": "Naum"
  },
  {
    "id": "habacuque",
    "name": "Habacuque"
  },
  {
    "id": "sofonias",
    "name": "Sofonias"
  },
  {
    "id": "ageu",
    "name": "Ageu"
  },
  {
    "id": "zacarias",
    "name": "Zacarias"
  },
  {
    "id": "malaquias",
    "name": "Malaquias"
  }
];
export const QUESTIONS = [
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual é o nome do profeta que recebeu de Deus a ordem de se casar com uma mulher de prostituição?",
    "option_a": "Oséias",
    "option_b": "Joel",
    "option_c": "Amós",
    "option_d": "Miquéias",
    "correct_answer": "A",
    "explanation": "Oséias 1:2 identifica o próprio profeta como aquele que recebeu essa ordem.",
    "hint": "O nome do livro é também o nome do profeta.",
    "source_type": "texto_biblico"
  },
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 11,
    "difficulty": "facil",
    "question": "Em Oséias 11, como Deus descreve seu relacionamento com Israel?",
    "option_a": "Como um comerciante",
    "option_b": "Como um pai que ensinou seu filho a andar",
    "option_c": "Como um rei estrangeiro",
    "option_d": "Como um guerreiro derrotado",
    "correct_answer": "B",
    "explanation": "Oséias 11:1-3 usa a imagem de Deus ensinando Efraim a andar e tomando-o nos braços.",
    "hint": "A imagem é de cuidado paternal.",
    "source_type": "texto_biblico"
  },
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 6,
    "difficulty": "medio",
    "question": "O que Oséias 6:6 diz que Deus deseja mais do que sacrifícios?",
    "option_a": "Riquezas",
    "option_b": "Conhecimento de Deus",
    "option_c": "Vitórias militares",
    "option_d": "Construções",
    "correct_answer": "B",
    "explanation": "Oséias 6:6 afirma que Deus deseja misericórdia e conhecimento de Deus mais do que holocaustos e sacrifícios.",
    "hint": "A resposta envolve conhecer a Deus.",
    "source_type": "texto_biblico"
  },
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 14,
    "difficulty": "medio",
    "question": "Qual é o convite final do livro de Oséias?",
    "option_a": "Fugir para o Egito",
    "option_b": "Voltar ao Senhor",
    "option_c": "Construir um novo templo",
    "option_d": "Escolher um novo rei",
    "correct_answer": "B",
    "explanation": "Oséias 14:1 chama Israel a voltar ao Senhor, pois tropeçou em sua iniquidade.",
    "hint": "O capítulo final começa com um chamado de retorno.",
    "source_type": "texto_biblico"
  },
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 2,
    "difficulty": "dificil",
    "question": "No simbolismo de Oséias 2, o que representa a infidelidade de Israel?",
    "option_a": "A idolatria e a ruptura da aliança com Deus",
    "option_b": "A construção do templo",
    "option_c": "A invasão da Assíria apenas",
    "option_d": "A divisão das tribos no deserto",
    "correct_answer": "A",
    "explanation": "Oséias usa a imagem conjugal para denunciar a infidelidade espiritual de Israel, associada à idolatria.",
    "hint": "A metáfora central é a de um casamento rompido.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual desastre ocupa grande parte do capítulo 1 de Joel?",
    "option_a": "Uma enchente",
    "option_b": "Uma invasão de gafanhotos",
    "option_c": "Um terremoto",
    "option_d": "Uma seca no Egito",
    "correct_answer": "B",
    "explanation": "Joel 1 descreve uma devastação causada por gafanhotos e convoca o povo ao lamento e ao jejum.",
    "hint": "O desastre é descrito como uma praga de insetos.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 2,
    "difficulty": "facil",
    "question": "O que Deus promete derramar sobre toda carne em Joel 2?",
    "option_a": "O seu Espírito",
    "option_b": "O seu ouro",
    "option_c": "A sua espada",
    "option_d": "O seu templo",
    "correct_answer": "A",
    "explanation": "Joel 2:28 anuncia: Deus derramará o seu Espírito sobre toda carne.",
    "hint": "É a promessa associada a filhos e filhas profetizando.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 2,
    "difficulty": "medio",
    "question": "Qual atitude Joel 2:12-13 pede ao povo?",
    "option_a": "Voltar ao Senhor de todo o coração",
    "option_b": "Migrar para outra terra",
    "option_c": "Construir uma fortaleza",
    "option_d": "Parar de orar",
    "correct_answer": "A",
    "explanation": "Joel chama o povo a voltar ao Senhor com jejum, choro e pranto, rasgando o coração.",
    "hint": "O chamado é interior, não apenas externo.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Segundo Joel 3, onde as nações são reunidas para julgamento?",
    "option_a": "Vale de Josafá",
    "option_b": "Monte Carmelo",
    "option_c": "Vale de Elá",
    "option_d": "Deserto do Sinai",
    "correct_answer": "A",
    "explanation": "Joel 3:2 e 12 menciona o vale de Josafá como lugar do julgamento das nações.",
    "hint": "O nome significa associado ao julgamento do Senhor.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 2,
    "difficulty": "dificil",
    "question": "Qual fenômeno é citado junto à promessa do Espírito e aos sinais no céu?",
    "option_a": "O sol se converterá em trevas e a lua em sangue",
    "option_b": "O mar se tornará doce",
    "option_c": "As montanhas desaparecerão",
    "option_d": "A chuva cessará por quarenta anos",
    "correct_answer": "A",
    "explanation": "Joel 2:30-31 menciona sinais no céu, incluindo sol em trevas e lua em sangue antes do grande e terrível dia do Senhor.",
    "hint": "São sinais celestes.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual era a profissão de Amós antes de exercer seu ministério profético?",
    "option_a": "Pastor de ovelhas e cultivador de sicômoros",
    "option_b": "Sacerdote",
    "option_c": "Rei",
    "option_d": "Pescador",
    "correct_answer": "A",
    "explanation": "Amós 1:1 e 7:14 apresentam Amós como pastor e cultivador de sicômoros.",
    "hint": "Ele não se apresenta como membro de uma escola profética.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 5,
    "difficulty": "facil",
    "question": "O que Amós 5:24 diz que deve correr como um rio?",
    "option_a": "O ouro",
    "option_b": "A justiça",
    "option_c": "O vinho",
    "option_d": "A guerra",
    "correct_answer": "B",
    "explanation": "Amós 5:24 compara a justiça a águas e o juízo à correnteza de um ribeiro perene.",
    "hint": "É uma das imagens mais conhecidas do livro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Qual princípio Amós 3:3 apresenta?",
    "option_a": "Dois andarão juntos se não houver acordo entre eles",
    "option_b": "Todo rei é justo",
    "option_c": "Israel nunca será julgado",
    "option_d": "Profetas não precisam ouvir Deus",
    "correct_answer": "A",
    "explanation": "Amós 3:3 pergunta se duas pessoas podem andar juntas sem estarem de acordo.",
    "hint": "É uma pergunta sobre concordância e caminhada conjunta.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 7,
    "difficulty": "medio",
    "question": "O que Amós vê em uma das primeiras visões do capítulo 7?",
    "option_a": "Um cesto de frutas de verão",
    "option_b": "Uma arca",
    "option_c": "Um carro de fogo",
    "option_d": "Uma escada",
    "correct_answer": "A",
    "explanation": "Amós 8:1-2 registra a visão de um cesto de frutas de verão, símbolo da proximidade do fim de Israel.",
    "hint": "A visão está no capítulo 8.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 8,
    "difficulty": "dificil",
    "question": "Na visão do cesto de frutas de verão, qual jogo de palavras aparece?",
    "option_a": "Fruta de verão e fim chegou",
    "option_b": "Chuva e bênção",
    "option_c": "Rei e sacerdote",
    "option_d": "Templo e altar",
    "correct_answer": "A",
    "explanation": "Amós 8:2 usa um jogo de palavras em hebraico entre fruta de verão e fim, indicando o fim de Israel.",
    "hint": "A visão anuncia que o fim chegou.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual nação é o principal alvo da profecia de Obadias?",
    "option_a": "Edom",
    "option_b": "Egito",
    "option_c": "Assíria",
    "option_d": "Moabe",
    "correct_answer": "A",
    "explanation": "Obadias é uma profecia contra Edom.",
    "hint": "Edom é o povo descendente de Esaú.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Edom é associado a qual ancestral?",
    "option_a": "Jacó",
    "option_b": "Esaú",
    "option_c": "Isaque",
    "option_d": "José",
    "correct_answer": "B",
    "explanation": "Edom está ligado a Esaú, irmão de Jacó, conforme Gênesis.",
    "hint": "Esaú recebeu o nome Edom.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "medio",
    "question": "Por que Edom é condenado em Obadias?",
    "option_a": "Por sua violência contra seu irmão Jacó",
    "option_b": "Por construir o templo",
    "option_c": "Por abandonar o Egito",
    "option_d": "Por cultivar oliveiras",
    "correct_answer": "A",
    "explanation": "Obadias 10-14 condena a violência e a participação de Edom na desgraça de Judá.",
    "hint": "O texto fala de violência contra o irmão.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "medio",
    "question": "O que Obadias 17 promete que haverá no monte Sião?",
    "option_a": "Livramento e santidade",
    "option_b": "Uma grande frota",
    "option_c": "Uma nova pirâmide",
    "option_d": "Um exército estrangeiro",
    "correct_answer": "A",
    "explanation": "Obadias 17 afirma que no monte Sião haverá livramento e ele será santo.",
    "hint": "É uma promessa para Sião.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "dificil",
    "question": "Qual é a ideia central do final de Obadias sobre o reino?",
    "option_a": "O reino será do Senhor",
    "option_b": "Edom governará para sempre",
    "option_c": "Babilônia dominará Judá",
    "option_d": "Não haverá restauração",
    "correct_answer": "A",
    "explanation": "Obadias 21 termina com a declaração de que o reino será do Senhor.",
    "hint": "É a frase final do livro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Para qual cidade Jonas foi enviado para pregar?",
    "option_a": "Nínive",
    "option_b": "Jerusalém",
    "option_c": "Samaria",
    "option_d": "Babilônia",
    "correct_answer": "A",
    "explanation": "Jonas 1:2 ordena que o profeta vá a Nínive para anunciar sua mensagem.",
    "hint": "Era a grande cidade da Assíria.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 2,
    "difficulty": "facil",
    "question": "O que engoliu Jonas depois que ele foi lançado ao mar?",
    "option_a": "Um grande peixe",
    "option_b": "Um crocodilo",
    "option_c": "Uma baleia mencionada pelo nome",
    "option_d": "Um navio",
    "correct_answer": "A",
    "explanation": "Jonas 1:17 diz que o Senhor preparou um grande peixe para engolir Jonas.",
    "hint": "O texto chama de grande peixe.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Como os ninivitas reagiram à pregação de Jonas?",
    "option_a": "Arrependeram-se e proclamaram jejum",
    "option_b": "Ignoraram a mensagem",
    "option_c": "Prenderam Jonas",
    "option_d": "Foram para Jerusalém",
    "correct_answer": "A",
    "explanation": "Jonas 3 descreve arrependimento, jejum e clamor a Deus desde o povo até o rei.",
    "hint": "O rei também participou do jejum.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 4,
    "difficulty": "medio",
    "question": "Por que Jonas ficou descontente depois da misericórdia de Deus para Nínive?",
    "option_a": "Porque Deus não destruiu a cidade",
    "option_b": "Porque perdeu o barco",
    "option_c": "Porque não recebeu pagamento",
    "option_d": "Porque o peixe voltou",
    "correct_answer": "A",
    "explanation": "Jonas 4:1-2 mostra que Jonas ficou irado porque Deus teve misericórdia e não executou o juízo anunciado.",
    "hint": "Jonas já sabia que Deus era misericordioso.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 4,
    "difficulty": "dificil",
    "question": "Que planta Deus fez crescer para dar sombra a Jonas?",
    "option_a": "Uma videira",
    "option_b": "Um mamoeiro",
    "option_c": "Uma planta chamada mamona na tradição portuguesa",
    "option_d": "Uma figueira",
    "correct_answer": "C",
    "explanation": "Jonas 4:6 fala de uma planta que cresceu para fazer sombra; traduções portuguesas variam na identificação, frequentemente usando mamona ou planta de rícino.",
    "hint": "O texto enfatiza que Deus preparou a planta e depois a fez secar.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "De onde era Miquéias?",
    "option_a": "Moresete",
    "option_b": "Belém",
    "option_c": "Jericó",
    "option_d": "Tiro",
    "correct_answer": "A",
    "explanation": "Miquéias 1:1 identifica o profeta como morastita, isto é, de Moresete.",
    "hint": "O nome do lugar aparece no início do livro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 5,
    "difficulty": "facil",
    "question": "Qual cidade é mencionada como origem do governante prometido?",
    "option_a": "Jerusalém",
    "option_b": "Belém Efrata",
    "option_c": "Nínive",
    "option_d": "Hebrom",
    "correct_answer": "B",
    "explanation": "Miquéias 5:2 menciona Belém Efrata como pequena entre os clãs de Judá.",
    "hint": "É uma cidade pequena de Judá.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 6,
    "difficulty": "medio",
    "question": "Segundo Miquéias 6:8, o que o Senhor requer do ser humano?",
    "option_a": "Praticar a justiça, amar a misericórdia e andar humildemente com Deus",
    "option_b": "Construir grandes palácios",
    "option_c": "Oferecer milhares de cavalos",
    "option_d": "Conquistar outras nações",
    "correct_answer": "A",
    "explanation": "Miquéias 6:8 resume o chamado ético em justiça, misericórdia e humildade diante de Deus.",
    "hint": "São três verbos/ideias centrais.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 4,
    "difficulty": "medio",
    "question": "O que Miquéias 4:3 diz que as nações transformarão?",
    "option_a": "Espadas em arados e lanças em foices",
    "option_b": "Arados em espadas",
    "option_c": "Templos em palácios",
    "option_d": "Rios em estradas",
    "correct_answer": "A",
    "explanation": "Miquéias 4:3 descreve a transformação de armas de guerra em instrumentos agrícolas.",
    "hint": "A imagem é de paz e cultivo.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 3,
    "difficulty": "dificil",
    "question": "Qual crítica Miquéias faz aos líderes que deveriam conhecer a justiça?",
    "option_a": "Eles aborreciam o bem e amavam o mal",
    "option_b": "Eles abandonaram a agricultura",
    "option_c": "Eles reconstruíram Nínive",
    "option_d": "Eles serviam como sacerdotes fiéis",
    "correct_answer": "A",
    "explanation": "Miquéias 3:1-3 acusa chefes e líderes de odiar o direito e praticar violência contra o povo.",
    "hint": "A crítica é dirigida aos líderes de Israel.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Contra qual cidade é dirigida a profecia de Naum?",
    "option_a": "Nínive",
    "option_b": "Jerusalém",
    "option_c": "Tiro",
    "option_d": "Damasco",
    "correct_answer": "A",
    "explanation": "Naum 1:1 apresenta a sentença contra Nínive.",
    "hint": "É a capital assíria.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Como Naum descreve o Senhor em relação à ira?",
    "option_a": "Tardio em irar-se e grande em poder",
    "option_b": "Fraco e indeciso",
    "option_c": "Sempre irado sem misericórdia",
    "option_d": "Indiferente ao mal",
    "correct_answer": "A",
    "explanation": "Naum 1:3 afirma que o Senhor é tardio em irar-se e grande em poder, sem deixar impune o culpado.",
    "hint": "O verso combina paciência e justiça.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 2,
    "difficulty": "medio",
    "question": "Qual imagem aparece na descrição da queda de Nínive?",
    "option_a": "Carros correndo pelas ruas e portas dos rios abertas",
    "option_b": "Um templo sendo reconstruído",
    "option_c": "Um exército chegando de Jerusalém",
    "option_d": "Uma seca no deserto",
    "correct_answer": "A",
    "explanation": "Naum 2 descreve de forma poética o ataque e a queda de Nínive, incluindo carros e a abertura das portas dos rios.",
    "hint": "A cidade está sob ataque.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Por que Nínive é chamada de cidade sanguinária?",
    "option_a": "Por sua violência, mentira e exploração",
    "option_b": "Por seus muitos jardins",
    "option_c": "Por sua riqueza agrícola",
    "option_d": "Por ser pequena",
    "correct_answer": "A",
    "explanation": "Naum 3:1 acusa Nínive de sangue, mentira, roubo e violência.",
    "hint": "A expressão aparece no início do capítulo 3.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 3,
    "difficulty": "dificil",
    "question": "Qual é o destino anunciado para Nínive?",
    "option_a": "Ser destruída e não ter cura para sua ferida",
    "option_b": "Ser reconstruída como capital de Judá",
    "option_c": "Governar o Egito",
    "option_d": "Receber um novo templo",
    "correct_answer": "A",
    "explanation": "Naum 3:7-19 descreve a queda de Nínive como irreversível diante das nações.",
    "hint": "O final do livro não anuncia restauração de Nínive.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 1,
    "difficulty": "facil",
    "question": "O que Habacuque faz principalmente no início do livro?",
    "option_a": "Questiona a Deus sobre a violência e a injustiça",
    "option_b": "Constrói um altar",
    "option_c": "Foge para o Egito",
    "option_d": "Interpreta sonhos de Nabucodonosor",
    "correct_answer": "A",
    "explanation": "Habacuque começa apresentando perguntas e queixas sobre a violência e a aparente demora da justiça.",
    "hint": "O livro tem forma de diálogo entre profeta e Deus.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 2,
    "difficulty": "facil",
    "question": "Qual frase famosa aparece em Habacuque 2:4?",
    "option_a": "O justo viverá pela sua fé",
    "option_b": "O Senhor é meu pastor",
    "option_c": "Olho por olho",
    "option_d": "Tudo é vaidade",
    "correct_answer": "A",
    "explanation": "Habacuque 2:4 afirma: o justo viverá pela sua fé/fidelidade, conforme a tradução.",
    "hint": "É uma frase central do livro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 2,
    "difficulty": "medio",
    "question": "O que Deus manda Habacuque fazer com a visão?",
    "option_a": "Escrevê-la claramente em tábuas",
    "option_b": "Escondê-la",
    "option_c": "Apagá-la",
    "option_d": "Entregá-la ao rei do Egito",
    "correct_answer": "A",
    "explanation": "Habacuque 2:2 ordena que a visão seja escrita claramente em tábuas para que possa ser lida.",
    "hint": "A instrução é escrever a visão.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Apesar da crise, como termina a oração de Habacuque?",
    "option_a": "Com alegria e confiança em Deus",
    "option_b": "Com uma fuga",
    "option_c": "Com uma coroação",
    "option_d": "Com silêncio absoluto",
    "correct_answer": "A",
    "explanation": "Habacuque 3:17-19 reconhece a falta de frutos e rebanhos, mas afirma alegria no Senhor e confiança em Deus.",
    "hint": "A alegria não depende da prosperidade.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 1,
    "difficulty": "dificil",
    "question": "Qual povo Deus diz que levantará como instrumento de juízo?",
    "option_a": "Os caldeus",
    "option_b": "Os filisteus",
    "option_c": "Os egípcios",
    "option_d": "Os edomitas",
    "correct_answer": "A",
    "explanation": "Habacuque 1:6 identifica os caldeus como povo que Deus levantaria para executar juízo.",
    "hint": "Caldeus é uma designação associada aos babilônios.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Quem é identificado como pai de Sofonias?",
    "option_a": "Cusi",
    "option_b": "Amós",
    "option_c": "Hulda",
    "option_d": "Ezequias",
    "correct_answer": "A",
    "explanation": "Sofonias 1:1 começa com a genealogia e identifica Sofonias como filho de Cusi.",
    "hint": "O nome aparece no primeiro versículo.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual expressão marca o anúncio de juízo em Sofonias?",
    "option_a": "O dia do Senhor",
    "option_b": "O ano do jubileu",
    "option_c": "A festa das colheitas",
    "option_d": "A noite do rei",
    "correct_answer": "A",
    "explanation": "O livro repete a expressão dia do Senhor como momento de juízo.",
    "hint": "É o tema temporal mais destacado.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 2,
    "difficulty": "medio",
    "question": "O que Sofonias 2:3 recomenda buscar?",
    "option_a": "O Senhor, a justiça e a humildade",
    "option_b": "Riquezas e poder",
    "option_c": "A Assíria",
    "option_d": "Um novo palácio",
    "correct_answer": "A",
    "explanation": "Sofonias 2:3 chama os humildes da terra a buscar o Senhor, a justiça e a humildade.",
    "hint": "São três elementos no convite.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Como termina o livro de Sofonias?",
    "option_a": "Com promessa de restauração e alegria de Deus sobre seu povo",
    "option_b": "Com a queda de Jerusalém sem esperança",
    "option_c": "Com uma guerra no Egito",
    "option_d": "Com a morte do profeta",
    "correct_answer": "A",
    "explanation": "Sofonias 3:14-20 termina com restauração, reunião dos dispersos e alegria associada à presença de Deus no meio do povo.",
    "hint": "O final muda do juízo para a restauração.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 3,
    "difficulty": "dificil",
    "question": "Qual cidade é mencionada entre os alvos de juízo no livro?",
    "option_a": "Nínive",
    "option_b": "Belém",
    "option_c": "Hebrom",
    "option_d": "Damasco",
    "correct_answer": "A",
    "explanation": "Sofonias 2:13-15 anuncia juízo contra a Assíria e Nínive, descrita como cidade desolada.",
    "hint": "A cidade assíria aparece explicitamente no capítulo 2.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual obra Ageu incentiva o povo a retomar?",
    "option_a": "A reconstrução do templo",
    "option_b": "A construção de uma frota",
    "option_c": "A muralha de Jericó",
    "option_d": "O palácio do rei",
    "correct_answer": "A",
    "explanation": "Ageu 1:8 chama o povo a subir ao monte, trazer madeira e edificar a casa de Deus.",
    "hint": "O templo é chamado de casa do Senhor.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Quem governava Judá como governador no contexto de Ageu?",
    "option_a": "Zorobabel",
    "option_b": "Elias",
    "option_c": "Ezequias",
    "option_d": "Saul",
    "correct_answer": "A",
    "explanation": "Ageu 1:1 identifica Zorobabel, filho de Sealtiel, como governador de Judá.",
    "hint": "Ele aparece ao lado de Josué, o sumo sacerdote.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 1,
    "difficulty": "medio",
    "question": "Quem era o sumo sacerdote mencionado junto a Zorobabel?",
    "option_a": "Josué, filho de Jeozadaque",
    "option_b": "Arão",
    "option_c": "Eli",
    "option_d": "Zadoque",
    "correct_answer": "A",
    "explanation": "Ageu 1:1 e outros textos do livro mencionam Josué, filho de Jeozadaque, como sumo sacerdote.",
    "hint": "Não é Josué, sucessor de Moisés.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 2,
    "difficulty": "medio",
    "question": "O que Deus promete em Ageu 2:9 sobre a glória da casa?",
    "option_a": "A glória desta última casa seria maior que a da primeira",
    "option_b": "A casa seria abandonada",
    "option_c": "O templo seria transferido para o Egito",
    "option_d": "Não haveria templo",
    "correct_answer": "A",
    "explanation": "Ageu 2:9 promete que a glória desta última casa seria maior que a primeira e anuncia paz.",
    "hint": "A comparação é entre a casa anterior e a reconstruída.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 2,
    "difficulty": "dificil",
    "question": "Qual imagem política aparece em Ageu 2:22?",
    "option_a": "Tronos serão derrubados e reinos serão destruídos",
    "option_b": "Israel dominará o Egito imediatamente",
    "option_c": "A Assíria voltará a governar",
    "option_d": "Zorobabel será coroado rei de todas as nações",
    "correct_answer": "A",
    "explanation": "Ageu 2:22 fala em derrubar tronos e destruir forças de reinos, dentro da mensagem escatológica do profeta.",
    "hint": "A linguagem é de abalo dos poderes políticos.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual era a principal mensagem inicial de Zacarias 1:3?",
    "option_a": "Voltai para mim, e eu me voltarei para vós",
    "option_b": "Fugi para o Egito",
    "option_c": "Não construam o templo",
    "option_d": "Escolham outro rei",
    "correct_answer": "A",
    "explanation": "Zacarias 1:3 chama o povo a retornar ao Senhor e promete que o Senhor se voltará para eles.",
    "hint": "É um chamado ao retorno.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 5,
    "difficulty": "facil",
    "question": "O que Zacarias vê em uma das visões do capítulo 5?",
    "option_a": "Um rolo voante",
    "option_b": "Uma arca de Noé",
    "option_c": "Um peixe gigante",
    "option_d": "Uma coroa de ferro",
    "correct_answer": "A",
    "explanation": "Zacarias 5:1 descreve um rolo voante.",
    "hint": "É uma visão escrita e voadora.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 4,
    "difficulty": "medio",
    "question": "Na visão do capítulo 4, o que representa o azeite em relação às duas oliveiras?",
    "option_a": "A provisão do Espírito de Deus",
    "option_b": "A riqueza do rei",
    "option_c": "A força militar",
    "option_d": "A água do templo",
    "correct_answer": "A",
    "explanation": "Zacarias 4 enfatiza a ação do Espírito: não por força nem por poder, mas pelo Espírito do Senhor.",
    "hint": "O verso 6 fornece a chave da visão.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 9,
    "difficulty": "medio",
    "question": "Qual rei é descrito chegando a Jerusalém montado em um jumento?",
    "option_a": "Um rei justo e salvador",
    "option_b": "O rei da Assíria",
    "option_c": "O faraó do Egito",
    "option_d": "Nabucodonosor",
    "correct_answer": "A",
    "explanation": "Zacarias 9:9 descreve um rei justo, salvador e humilde, montado em jumento.",
    "hint": "A descrição é de um rei humilde.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 12,
    "difficulty": "dificil",
    "question": "Qual expressão aparece em Zacarias 12:10 sobre o futuro arrependimento?",
    "option_a": "Olharão para aquele a quem traspassaram e prantearão",
    "option_b": "Não haverá arrependimento",
    "option_c": "Israel será levado ao Egito",
    "option_d": "Jerusalém será abandonada para sempre",
    "correct_answer": "A",
    "explanation": "Zacarias 12:10 descreve derramamento de espírito de graça e súplicas, seguido de lamento ao olhar para aquele que foi traspassado.",
    "hint": "É uma passagem de lamento e arrependimento.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual é a primeira pergunta de contestação registrada no diálogo de Malaquias?",
    "option_a": "Em que nos amaste?",
    "option_b": "Onde está Moisés?",
    "option_c": "Quem é o rei?",
    "option_d": "Quando virá Elias?",
    "correct_answer": "A",
    "explanation": "Malaquias 1:2 registra a pergunta do povo: em que nos amaste?",
    "hint": "Ela vem logo após Deus declarar seu amor por Jacó.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 3,
    "difficulty": "facil",
    "question": "Quem é prometido como mensageiro antes da chegada do Senhor?",
    "option_a": "Um mensageiro que prepararia o caminho",
    "option_b": "Um general romano",
    "option_c": "Um novo rei assírio",
    "option_d": "Um sacerdote de Samaria",
    "correct_answer": "A",
    "explanation": "Malaquias 3:1 fala do mensageiro que preparará o caminho diante do Senhor.",
    "hint": "A palavra-chave é mensageiro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 3,
    "difficulty": "medio",
    "question": "O que Malaquias 3:10 relaciona ao dízimo?",
    "option_a": "Trazer todos os dízimos à casa do tesouro",
    "option_b": "Guardar o dízimo em casa",
    "option_c": "Entregar somente ao rei",
    "option_d": "Usar o dízimo para guerra",
    "correct_answer": "A",
    "explanation": "Malaquias 3:10 chama a trazer todos os dízimos à casa do tesouro e apresenta a promessa de provisão.",
    "hint": "A expressão é casa do tesouro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 4,
    "difficulty": "medio",
    "question": "O que o final do livro de Malaquias promete enviar antes do grande e terrível dia do Senhor?",
    "option_a": "Elias, o profeta",
    "option_b": "Samuel",
    "option_c": "Jeremias",
    "option_d": "Natã",
    "correct_answer": "A",
    "explanation": "Malaquias 4:5 promete enviar Elias, o profeta, antes do grande e terrível dia do Senhor.",
    "hint": "É o último nome mencionado no livro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 2,
    "difficulty": "dificil",
    "question": "Qual problema dos sacerdotes é denunciado em Malaquias 2?",
    "option_a": "Desprezavam o nome de Deus e ofereciam sacrifícios inadequados",
    "option_b": "Construíam muitos altares",
    "option_c": "Recusavam-se a trabalhar no templo",
    "option_d": "Não conheciam a Lei de Moisés",
    "correct_answer": "A",
    "explanation": "Malaquias 1–2 denuncia sacerdotes que desprezavam o nome de Deus e aceitavam animais inadequados para sacrifício.",
    "hint": "A denúncia envolve a qualidade das ofertas.",
    "source_type": "texto_biblico"
  }
].map((q,i)=>({id:uuid(i+1),...q,order_index:i+1,active:true}));
export const ACHIEVEMENTS=[
{id:'11111111-1111-4111-8111-111111111111',code:'FIRST_GAME',name:'Primeira Partida',icon:'🎯',description:'Complete sua primeira partida.',criteria:{type:'attempts_count',value:1}},
{id:'11111111-1111-4111-8111-111111111112',code:'FIVE_GAMES',name:'5 Partidas',icon:'🔥',description:'Complete 5 partidas.',criteria:{type:'attempts_count',value:5}},
{id:'11111111-1111-4111-8111-111111111113',code:'TEN_GAMES',name:'10 Partidas',icon:'⚡',description:'Complete 10 partidas.',criteria:{type:'attempts_count',value:10}},
{id:'11111111-1111-4111-8111-111111111114',code:'PERFECT_SCORE',name:'100% de Acertos',icon:'💯',description:'Termine uma partida com todas as respostas corretas.',criteria:{type:'perfect_attempt',value:true}},
{id:'11111111-1111-4111-8111-111111111115',code:'TOP_TEN',name:'Top 10',icon:'🏅',description:'Entre no top 10 do ranking geral.',criteria:{type:'leaderboard_position',value:10}},
{id:'11111111-1111-4111-8111-111111111116',code:'FIRST_PLACE',name:'1º Lugar',icon:'👑',description:'Alcance o 1º lugar do ranking geral.',criteria:{type:'leaderboard_position',value:1}},
{id:'11111111-1111-4111-8111-111111111117',code:'PROPHETS_EXPERT',name:'Especialista nos Profetas',icon:'📖',description:'Acumule 100 respostas corretas e alcance 85% ou mais de acerto.',criteria:{type:'expert',correct:100,min_accuracy:85}}];
export default {PROPHETS,QUESTIONS,ACHIEVEMENTS};
