/** Banco oficial do Quiz dos Profetas Menores. 120 questões: 10 por profeta (12 livros). */
const uuid=(n)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
export const PROPHETS = [
  {
    "id": "oseias",
    "name": "Oséias"
  },
  {
    "id": "joel",
    "name": "Joel"
  },
  {
    "id": "amos",
    "name": "Amós"
  },
  {
    "id": "obadias",
    "name": "Obadias"
  },
  {
    "id": "jonas",
    "name": "Jonas"
  },
  {
    "id": "miqueias",
    "name": "Miquéias"
  },
  {
    "id": "naum",
    "name": "Naum"
  },
  {
    "id": "habacuque",
    "name": "Habacuque"
  },
  {
    "id": "sofonias",
    "name": "Sofonias"
  },
  {
    "id": "ageu",
    "name": "Ageu"
  },
  {
    "id": "zacarias",
    "name": "Zacarias"
  },
  {
    "id": "malaquias",
    "name": "Malaquias"
  }
];
export const QUESTIONS = [
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual é o nome do profeta que recebeu de Deus a ordem de se casar com uma mulher de prostituição?",
    "option_a": "Miquéias",
    "option_b": "Amós",
    "option_c": "Oséias",
    "option_d": "Joel",
    "correct_answer": "C",
    "explanation": "Oséias 1:2 identifica o próprio profeta como aquele que recebeu essa ordem.",
    "hint": "O nome do livro é também o nome do profeta.",
    "source_type": "texto_biblico"
  },
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 11,
    "difficulty": "facil",
    "question": "Em Oséias 11, como Deus descreve seu relacionamento com Israel?",
    "option_a": "Como um rei estrangeiro",
    "option_b": "Como um guerreiro derrotado",
    "option_c": "Como um comerciante",
    "option_d": "Como um pai que ensinou seu filho a andar",
    "correct_answer": "D",
    "explanation": "Oséias 11:1-3 usa a imagem de Deus ensinando Efraim a andar e tomando-o nos braços.",
    "hint": "A imagem é de cuidado paternal.",
    "source_type": "texto_biblico"
  },
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 6,
    "difficulty": "medio",
    "question": "O que Oséias 6:6 diz que Deus deseja mais do que sacrifícios?",
    "option_a": "Construções",
    "option_b": "Conhecimento de Deus",
    "option_c": "Vitórias militares",
    "option_d": "Riquezas",
    "correct_answer": "B",
    "explanation": "Oséias 6:6 afirma que Deus deseja misericórdia e conhecimento de Deus mais do que holocaustos e sacrifícios.",
    "hint": "A resposta envolve conhecer a Deus.",
    "source_type": "texto_biblico"
  },
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 14,
    "difficulty": "medio",
    "question": "Qual é o convite final do livro de Oséias?",
    "option_a": "Escolher um novo rei",
    "option_b": "Construir um novo templo",
    "option_c": "Voltar ao Senhor",
    "option_d": "Fugir para o Egito",
    "correct_answer": "C",
    "explanation": "Oséias 14:1 chama Israel a voltar ao Senhor, pois tropeçou em sua iniquidade.",
    "hint": "O capítulo final começa com um chamado de retorno.",
    "source_type": "texto_biblico"
  },
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 2,
    "difficulty": "dificil",
    "question": "No simbolismo de Oséias 2, o que representa a infidelidade de Israel?",
    "option_a": "A construção do templo",
    "option_b": "A idolatria e a ruptura da aliança com Deus",
    "option_c": "A invasão da Assíria apenas",
    "option_d": "A divisão das tribos no deserto",
    "correct_answer": "B",
    "explanation": "Oséias usa a imagem conjugal para denunciar a infidelidade espiritual de Israel, associada à idolatria.",
    "hint": "A metáfora central é a de um casamento rompido.",
    "source_type": "texto_biblico"
  },
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 3,
    "difficulty": "facil",
    "question": "O que Oséias fez para readquirir sua esposa, ilustrando o amor redentor de Deus?",
    "option_a": "Pagou com prata e cevada",
    "option_b": "Foi a um tribunal romano",
    "option_c": "Pediu ajuda ao rei da Assíria",
    "option_d": "Construiu um novo templo",
    "correct_answer": "A",
    "explanation": "Oséias 3:2 relata que o profeta comprou sua esposa por quinze moedas de prata e certa quantidade de cevada, simbolizando a redenção de Israel.",
    "hint": "O preço envolve dinheiro e um grão.",
    "source_type": "texto_biblico"
  },
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 4,
    "difficulty": "facil",
    "question": "Qual acusação abre a controvérsia de Deus com Israel em Oséias 4?",
    "option_a": "Não há conhecimento de Deus na terra",
    "option_b": "O rei foi deposto",
    "option_c": "O templo foi destruído",
    "option_d": "O povo é rico demais",
    "correct_answer": "A",
    "explanation": "Oséias 4:1 acusa a terra de faltar verdade, misericórdia e conhecimento de Deus.",
    "hint": "É uma falta de relacionamento com Deus.",
    "source_type": "texto_biblico"
  },
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 13,
    "difficulty": "medio",
    "question": "Qual pergunta desafiadora sobre a morte aparece em Oséias 13:14?",
    "option_a": "Quem construirá o templo?",
    "option_b": "Quando virá o novo rei?",
    "option_c": "Onde está a arca da aliança?",
    "option_d": "Onde está, ó morte, o teu aguilhão?",
    "correct_answer": "D",
    "explanation": "Oséias 13:14 desafia a morte e o Seol, texto depois citado em 1 Coríntios 15.",
    "hint": "É citado no Novo Testamento sobre a ressurreição.",
    "source_type": "texto_biblico"
  },
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 10,
    "difficulty": "medio",
    "question": "O que Oséias 10:12 convida o povo a semear?",
    "option_a": "Medo",
    "option_b": "Discórdia",
    "option_c": "Ouro",
    "option_d": "Justiça",
    "correct_answer": "D",
    "explanation": "Oséias 10:12 exorta: semeai para vós a justiça e colhei segundo a bondade.",
    "hint": "É um chamado agrícola com sentido moral.",
    "source_type": "texto_biblico"
  },
  {
    "book": "oseias",
    "book_name": "Oséias",
    "chapter": 5,
    "difficulty": "dificil",
    "question": "Em Oséias 5:15, o que Deus diz que fará até que o povo reconheça sua culpa?",
    "option_a": "Voltará ao seu lugar",
    "option_b": "Abandonará os profetas",
    "option_c": "Enviará outro dilúvio",
    "option_d": "Destruirá o mundo",
    "correct_answer": "A",
    "explanation": "Oséias 5:15 apresenta Deus retirando-se até que o povo, em angústia, busque a sua face.",
    "hint": "Deus se retira temporariamente.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual desastre ocupa grande parte do capítulo 1 de Joel?",
    "option_a": "Um terremoto",
    "option_b": "Uma invasão de gafanhotos",
    "option_c": "Uma enchente",
    "option_d": "Uma seca no Egito",
    "correct_answer": "B",
    "explanation": "Joel 1 descreve uma devastação causada por gafanhotos e convoca o povo ao lamento e ao jejum.",
    "hint": "O desastre é descrito como uma praga de insetos.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 2,
    "difficulty": "facil",
    "question": "O que Deus promete derramar sobre toda carne em Joel 2?",
    "option_a": "O seu ouro",
    "option_b": "O seu templo",
    "option_c": "A sua espada",
    "option_d": "O seu Espírito",
    "correct_answer": "D",
    "explanation": "Joel 2:28 anuncia: Deus derramará o seu Espírito sobre toda carne.",
    "hint": "É a promessa associada a filhos e filhas profetizando.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 2,
    "difficulty": "medio",
    "question": "Qual atitude Joel 2:12-13 pede ao povo?",
    "option_a": "Construir uma fortaleza",
    "option_b": "Migrar para outra terra",
    "option_c": "Parar de orar",
    "option_d": "Voltar ao Senhor de todo o coração",
    "correct_answer": "D",
    "explanation": "Joel chama o povo a voltar ao Senhor com jejum, choro e pranto, rasgando o coração.",
    "hint": "O chamado é interior, não apenas externo.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Segundo Joel 3, onde as nações são reunidas para julgamento?",
    "option_a": "Monte Carmelo",
    "option_b": "Vale de Elá",
    "option_c": "Vale de Josafá",
    "option_d": "Deserto do Sinai",
    "correct_answer": "C",
    "explanation": "Joel 3:2 e 12 menciona o vale de Josafá como lugar do julgamento das nações.",
    "hint": "O nome significa associado ao julgamento do Senhor.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 2,
    "difficulty": "dificil",
    "question": "Qual fenômeno é citado junto à promessa do Espírito e aos sinais no céu?",
    "option_a": "A chuva cessará por quarenta anos",
    "option_b": "As montanhas desaparecerão",
    "option_c": "O mar se tornará doce",
    "option_d": "O sol se converterá em trevas e a lua em sangue",
    "correct_answer": "D",
    "explanation": "Joel 2:30-31 menciona sinais no céu, incluindo sol em trevas e lua em sangue antes do grande e terrível dia do Senhor.",
    "hint": "São sinais celestes.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Quem Joel convoca a despertar e chorar por causa da devastação em Joel 1:5?",
    "option_a": "Os exércitos vizinhos",
    "option_b": "Os sacerdotes apenas",
    "option_c": "Os bêbados",
    "option_d": "Os reis estrangeiros",
    "correct_answer": "C",
    "explanation": "Joel 1:5 chama os bêbados a despertarem e chorarem pela perda do vinho novo.",
    "hint": "Estão associados à bebida.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 2,
    "difficulty": "facil",
    "question": "O que o povo deve tocar em Sião para anunciar o perigo em Joel 2:1?",
    "option_a": "A trombeta",
    "option_b": "Os címbalos",
    "option_c": "O tambor",
    "option_d": "A harpa",
    "correct_answer": "A",
    "explanation": "Joel 2:1 ordena tocar a trombeta em Sião para soar o alarme.",
    "hint": "É um instrumento de alerta.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 2,
    "difficulty": "medio",
    "question": "O que Deus promete restituir em Joel 2:25?",
    "option_a": "Os anos que o gafanhoto comeu",
    "option_b": "Os tronos derrubados",
    "option_c": "As tribos perdidas",
    "option_d": "As muralhas da cidade",
    "correct_answer": "A",
    "explanation": "Joel 2:25 promete restituir os anos devorados pelo gafanhoto, símbolo de restauração após o juízo.",
    "hint": "É uma promessa de compensação pelo tempo perdido.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Em Joel 3:10, o que as nações são chamadas a transformar em espadas?",
    "option_a": "Suas tendas",
    "option_b": "As relhas dos seus arados",
    "option_c": "Seus rebanhos",
    "option_d": "Seus templos",
    "correct_answer": "B",
    "explanation": "Joel 3:10 inverte a imagem de paz (vista em Miquéias e Isaías), convocando as nações à guerra: batei as relhas em espadas.",
    "hint": "É o oposto da imagem de paz de Miquéias 4:3.",
    "source_type": "texto_biblico"
  },
  {
    "book": "joel",
    "book_name": "Joel",
    "chapter": 2,
    "difficulty": "dificil",
    "question": "Segundo Joel 2:32, o que acontecerá a todo aquele que invocar o nome do Senhor?",
    "option_a": "Será salvo",
    "option_b": "Perderá seus bens",
    "option_c": "Será exilado",
    "option_d": "Será esquecido",
    "correct_answer": "A",
    "explanation": "Joel 2:32 promete que todo aquele que invocar o nome do Senhor será salvo, texto citado em Atos 2 e Romanos 10.",
    "hint": "É citado por Pedro no dia de Pentecostes.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual era a profissão de Amós antes de exercer seu ministério profético?",
    "option_a": "Rei",
    "option_b": "Pastor de ovelhas e cultivador de sicômoros",
    "option_c": "Pescador",
    "option_d": "Sacerdote",
    "correct_answer": "B",
    "explanation": "Amós 1:1 e 7:14 apresentam Amós como pastor e cultivador de sicômoros.",
    "hint": "Ele não se apresenta como membro de uma escola profética.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 5,
    "difficulty": "facil",
    "question": "O que Amós 5:24 diz que deve correr como um rio?",
    "option_a": "O ouro",
    "option_b": "O vinho",
    "option_c": "A guerra",
    "option_d": "A justiça",
    "correct_answer": "D",
    "explanation": "Amós 5:24 compara a justiça a águas e o juízo à correnteza de um ribeiro perene.",
    "hint": "É uma das imagens mais conhecidas do livro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Qual princípio Amós 3:3 apresenta?",
    "option_a": "Dois andarão juntos se não houver acordo entre eles",
    "option_b": "Todo rei é justo",
    "option_c": "Israel nunca será julgado",
    "option_d": "Profetas não precisam ouvir Deus",
    "correct_answer": "A",
    "explanation": "Amós 3:3 pergunta se duas pessoas podem andar juntas sem estarem de acordo.",
    "hint": "É uma pergunta sobre concordância e caminhada conjunta.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 7,
    "difficulty": "medio",
    "question": "O que Amós vê em uma das primeiras visões do capítulo 7?",
    "option_a": "Uma escada",
    "option_b": "Uma arca",
    "option_c": "Um cesto de frutas de verão",
    "option_d": "Um carro de fogo",
    "correct_answer": "C",
    "explanation": "Amós 8:1-2 registra a visão de um cesto de frutas de verão, símbolo da proximidade do fim de Israel.",
    "hint": "A visão está no capítulo 8.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 8,
    "difficulty": "dificil",
    "question": "Na visão do cesto de frutas de verão, qual jogo de palavras aparece?",
    "option_a": "Chuva e bênção",
    "option_b": "Fruta de verão e fim chegou",
    "option_c": "Templo e altar",
    "option_d": "Rei e sacerdote",
    "correct_answer": "B",
    "explanation": "Amós 8:2 usa um jogo de palavras em hebraico entre fruta de verão e fim, indicando o fim de Israel.",
    "hint": "A visão anuncia que o fim chegou.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 4,
    "difficulty": "facil",
    "question": "Como Amós 4:1 chama as mulheres opressoras de Samaria?",
    "option_a": "Leoas do deserto",
    "option_b": "Vacas de Basã",
    "option_c": "Pombas do vale",
    "option_d": "Águias da montanha",
    "correct_answer": "B",
    "explanation": "Amós 4:1 usa a expressão vacas de Basã para denunciar mulheres que oprimiam os pobres.",
    "hint": "É uma comparação com um animal de pastagem rica.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 9,
    "difficulty": "facil",
    "question": "O que Deus promete restaurar em Amós 9:11?",
    "option_a": "O tabernáculo caído de Davi",
    "option_b": "O templo de Baal",
    "option_c": "O palácio do Egito",
    "option_d": "A muralha de Nínive",
    "correct_answer": "A",
    "explanation": "Amós 9:11 promete levantar o tabernáculo caído de Davi, texto citado em Atos 15.",
    "hint": "É uma promessa messiânica ligada à linhagem de Davi.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 2,
    "difficulty": "medio",
    "question": "Do que Israel é acusado em Amós 2:6, ao vender pessoas?",
    "option_a": "Vender terras para o Egito",
    "option_b": "Vender animais sagrados",
    "option_c": "Vender o justo por prata e o pobre por um par de sandálias",
    "option_d": "Vender armas para a Assíria",
    "correct_answer": "C",
    "explanation": "Amós 2:6 denuncia a venda do justo por dinheiro e do pobre por um simples par de sandálias.",
    "hint": "É uma denúncia de injustiça social extrema.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 6,
    "difficulty": "medio",
    "question": "Contra quem é o \"ai\" pronunciado em Amós 6:1?",
    "option_a": "Os estrangeiros pobres",
    "option_b": "Os pastores humildes",
    "option_c": "Os que vivem sossegados em Sião",
    "option_d": "Os sacerdotes fiéis",
    "correct_answer": "C",
    "explanation": "Amós 6:1 pronuncia ai sobre os que vivem despreocupados e confiantes em Sião e em Samaria.",
    "hint": "É uma crítica à complacência dos líderes.",
    "source_type": "texto_biblico"
  },
  {
    "book": "amos",
    "book_name": "Amós",
    "chapter": 7,
    "difficulty": "dificil",
    "question": "Quem ordenou que Amós fugisse para Judá e parasse de profetizar em Betel?",
    "option_a": "O rei da Assíria",
    "option_b": "Um profeta rival",
    "option_c": "Jeroboão pessoalmente",
    "option_d": "Amazias, sacerdote de Betel",
    "correct_answer": "D",
    "explanation": "Amós 7:10-13 narra o confronto com Amazias, sacerdote de Betel, que expulsou Amós, ao que o profeta respondeu que não era profeta profissional, mas pastor chamado por Deus.",
    "hint": "É o sacerdote do santuário real de Betel.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual nação é o principal alvo da profecia de Obadias?",
    "option_a": "Egito",
    "option_b": "Moabe",
    "option_c": "Assíria",
    "option_d": "Edom",
    "correct_answer": "D",
    "explanation": "Obadias é uma profecia contra Edom.",
    "hint": "Edom é o povo descendente de Esaú.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Edom é associado a qual ancestral?",
    "option_a": "Isaque",
    "option_b": "Esaú",
    "option_c": "Jacó",
    "option_d": "José",
    "correct_answer": "B",
    "explanation": "Edom está ligado a Esaú, irmão de Jacó, conforme Gênesis.",
    "hint": "Esaú recebeu o nome Edom.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "medio",
    "question": "Por que Edom é condenado em Obadias?",
    "option_a": "Por cultivar oliveiras",
    "option_b": "Por construir o templo",
    "option_c": "Por abandonar o Egito",
    "option_d": "Por sua violência contra seu irmão Jacó",
    "correct_answer": "D",
    "explanation": "Obadias 10-14 condena a violência e a participação de Edom na desgraça de Judá.",
    "hint": "O texto fala de violência contra o irmão.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "medio",
    "question": "O que Obadias 17 promete que haverá no monte Sião?",
    "option_a": "Um exército estrangeiro",
    "option_b": "Uma nova pirâmide",
    "option_c": "Livramento e santidade",
    "option_d": "Uma grande frota",
    "correct_answer": "C",
    "explanation": "Obadias 17 afirma que no monte Sião haverá livramento e ele será santo.",
    "hint": "É uma promessa para Sião.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "dificil",
    "question": "Qual é a ideia central do final de Obadias sobre o reino?",
    "option_a": "O reino será do Senhor",
    "option_b": "Não haverá restauração",
    "option_c": "Edom governará para sempre",
    "option_d": "Babilônia dominará Judá",
    "correct_answer": "A",
    "explanation": "Obadias 21 termina com a declaração de que o reino será do Senhor.",
    "hint": "É a frase final do livro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Segundo Obadias 3, o que enganou o coração de Edom?",
    "option_a": "A fome",
    "option_b": "A ignorância",
    "option_c": "A pobreza",
    "option_d": "A soberba",
    "correct_answer": "D",
    "explanation": "Obadias 3 diz que a soberba do coração de Edom o enganou, confiando em sua posição elevada nas rochas.",
    "hint": "É um pecado ligado ao orgulho.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Onde Edom habitava, segundo a descrição de Obadias 3?",
    "option_a": "Nas fendas das rochas, em lugar alto",
    "option_b": "Em barcos no mar Vermelho",
    "option_c": "Nas margens do rio Nilo",
    "option_d": "Em tendas no deserto do Sinai",
    "correct_answer": "A",
    "explanation": "Obadias 3 descreve Edom habitando nas fendas das rochas, confiante em sua altura e segurança.",
    "hint": "É uma região montanhosa e fortificada.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "medio",
    "question": "Qual foi a atitude de Edom quando estrangeiros saquearam Jerusalém, segundo Obadias 11?",
    "option_a": "Defendeu Jerusalém com seu exército",
    "option_b": "Ficou de lado e se comportou como um deles",
    "option_c": "Avisou os profetas com antecedência",
    "option_d": "Abrigou os refugiados de Judá",
    "correct_answer": "B",
    "explanation": "Obadias 11 acusa Edom de ficar de lado, omisso, comportando-se como um dos invasores.",
    "hint": "A culpa envolve omissão e cumplicidade.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "medio",
    "question": "Qual princípio de reciprocidade aparece em Obadias 15?",
    "option_a": "Quem semeia pouco colhe muito",
    "option_b": "Como fizeste, se fará a ti",
    "option_c": "Não haverá julgamento para nenhuma nação",
    "option_d": "O rico sempre vencerá",
    "correct_answer": "B",
    "explanation": "Obadias 15 anuncia que o dia do Senhor virá sobre todas as nações e o que Edom fez lhe será retribuído.",
    "hint": "É uma lei de causa e efeito no juízo divino.",
    "source_type": "texto_biblico"
  },
  {
    "book": "obadias",
    "book_name": "Obadias",
    "chapter": 1,
    "difficulty": "dificil",
    "question": "Em Obadias 18, a que a casa de Esaú é comparada diante do fogo de Jacó e José?",
    "option_a": "Um rio caudaloso",
    "option_b": "Ouro puro",
    "option_c": "Restolho, que será consumido",
    "option_d": "Uma torre inabalável",
    "correct_answer": "C",
    "explanation": "Obadias 18 descreve a casa de Jacó como fogo e a de Esaú como restolho, que será totalmente consumido.",
    "hint": "É um material seco e facilmente inflamável.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Para qual cidade Jonas foi enviado para pregar?",
    "option_a": "Nínive",
    "option_b": "Babilônia",
    "option_c": "Jerusalém",
    "option_d": "Samaria",
    "correct_answer": "A",
    "explanation": "Jonas 1:2 ordena que o profeta vá a Nínive para anunciar sua mensagem.",
    "hint": "Era a grande cidade da Assíria.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 2,
    "difficulty": "facil",
    "question": "O que engoliu Jonas depois que ele foi lançado ao mar?",
    "option_a": "Um navio",
    "option_b": "Um crocodilo",
    "option_c": "Um grande peixe",
    "option_d": "Uma baleia mencionada pelo nome",
    "correct_answer": "C",
    "explanation": "Jonas 1:17 diz que o Senhor preparou um grande peixe para engolir Jonas.",
    "hint": "O texto chama de grande peixe.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Como os ninivitas reagiram à pregação de Jonas?",
    "option_a": "Prenderam Jonas",
    "option_b": "Ignoraram a mensagem",
    "option_c": "Arrependeram-se e proclamaram jejum",
    "option_d": "Foram para Jerusalém",
    "correct_answer": "C",
    "explanation": "Jonas 3 descreve arrependimento, jejum e clamor a Deus desde o povo até o rei.",
    "hint": "O rei também participou do jejum.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 4,
    "difficulty": "medio",
    "question": "Por que Jonas ficou descontente depois da misericórdia de Deus para Nínive?",
    "option_a": "Porque perdeu o barco",
    "option_b": "Porque não recebeu pagamento",
    "option_c": "Porque o peixe voltou",
    "option_d": "Porque Deus não destruiu a cidade",
    "correct_answer": "D",
    "explanation": "Jonas 4:1-2 mostra que Jonas ficou irado porque Deus teve misericórdia e não executou o juízo anunciado.",
    "hint": "Jonas já sabia que Deus era misericordioso.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 4,
    "difficulty": "dificil",
    "question": "Que planta Deus fez crescer para dar sombra a Jonas?",
    "option_a": "Uma figueira",
    "option_b": "Um mamoeiro",
    "option_c": "Uma videira",
    "option_d": "Uma planta chamada mamona na tradição portuguesa",
    "correct_answer": "D",
    "explanation": "Jonas 4:6 fala de uma planta que cresceu para fazer sombra; traduções portuguesas variam na identificação, frequentemente usando mamona ou planta de rícino.",
    "hint": "O texto enfatiza que Deus preparou a planta e depois a fez secar.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Para onde Jonas tentou fugir em vez de ir a Nínive?",
    "option_a": "Társis",
    "option_b": "Damasco",
    "option_c": "Jerusalém",
    "option_d": "Babilônia",
    "correct_answer": "A",
    "explanation": "Jonas 1:3 relata que o profeta embarcou em um navio rumo a Társis, fugindo da presença do Senhor.",
    "hint": "Era uma cidade distante, na direção oposta a Nínive.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Como os marinheiros descobriram que Jonas era o responsável pela tempestade?",
    "option_a": "Lançaram sortes",
    "option_b": "Consultaram um oráculo egípcio",
    "option_c": "Jonas confessou espontaneamente logo no início",
    "option_d": "Um anjo apareceu",
    "correct_answer": "A",
    "explanation": "Jonas 1:7 relata que os marinheiros lançaram sortes, e a sorte caiu sobre Jonas.",
    "hint": "É um método antigo de decisão por acaso.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 2,
    "difficulty": "medio",
    "question": "O que Jonas declara sobre a salvação em sua oração de dentro do peixe (Jonas 2:9)?",
    "option_a": "A salvação vem dos sacerdotes",
    "option_b": "Não há salvação possível",
    "option_c": "A salvação pertence ao Senhor",
    "option_d": "A salvação depende dos marinheiros",
    "correct_answer": "C",
    "explanation": "Jonas 2:9 conclui a oração afirmando que a salvação pertence ao Senhor.",
    "hint": "É a frase de encerramento da oração no ventre do peixe.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Qual foi a mensagem exata que Jonas pregou em Nínive, segundo Jonas 3:4?",
    "option_a": "Os reis da terra se converterão",
    "option_b": "Ainda quarenta dias, e Nínive será destruída",
    "option_c": "Nínive será poupada para sempre",
    "option_d": "Israel será restaurado em breve",
    "correct_answer": "B",
    "explanation": "Jonas 3:4 registra o anúncio de julgamento em quarenta dias sobre Nínive.",
    "hint": "Envolve um prazo específico de dias.",
    "source_type": "texto_biblico"
  },
  {
    "book": "jonas",
    "book_name": "Jonas",
    "chapter": 4,
    "difficulty": "dificil",
    "question": "No argumento final de Deus a Jonas, quantas pessoas incapazes de discernir a mão direita da esquerda havia em Nínive?",
    "option_a": "Um milhão",
    "option_b": "Mais de cento e vinte mil",
    "option_c": "Doze mil",
    "option_d": "Exatamente cem",
    "correct_answer": "B",
    "explanation": "Jonas 4:11 menciona mais de cento e vinte mil pessoas em Nínive, além de muitos animais, como razão da compaixão de Deus.",
    "hint": "É um número alto, citado junto com os animais da cidade.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "De onde era Miquéias?",
    "option_a": "Jericó",
    "option_b": "Tiro",
    "option_c": "Moresete",
    "option_d": "Belém",
    "correct_answer": "C",
    "explanation": "Miquéias 1:1 identifica o profeta como morastita, isto é, de Moresete.",
    "hint": "O nome do lugar aparece no início do livro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 5,
    "difficulty": "facil",
    "question": "Qual cidade é mencionada como origem do governante prometido?",
    "option_a": "Nínive",
    "option_b": "Hebrom",
    "option_c": "Jerusalém",
    "option_d": "Belém Efrata",
    "correct_answer": "D",
    "explanation": "Miquéias 5:2 menciona Belém Efrata como pequena entre os clãs de Judá.",
    "hint": "É uma cidade pequena de Judá.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 6,
    "difficulty": "medio",
    "question": "Segundo Miquéias 6:8, o que o Senhor requer do ser humano?",
    "option_a": "Oferecer milhares de cavalos",
    "option_b": "Construir grandes palácios",
    "option_c": "Conquistar outras nações",
    "option_d": "Praticar a justiça, amar a misericórdia e andar humildemente com Deus",
    "correct_answer": "D",
    "explanation": "Miquéias 6:8 resume o chamado ético em justiça, misericórdia e humildade diante de Deus.",
    "hint": "São três verbos/ideias centrais.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 4,
    "difficulty": "medio",
    "question": "O que Miquéias 4:3 diz que as nações transformarão?",
    "option_a": "Templos em palácios",
    "option_b": "Espadas em arados e lanças em foices",
    "option_c": "Arados em espadas",
    "option_d": "Rios em estradas",
    "correct_answer": "B",
    "explanation": "Miquéias 4:3 descreve a transformação de armas de guerra em instrumentos agrícolas.",
    "hint": "A imagem é de paz e cultivo.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 3,
    "difficulty": "dificil",
    "question": "Qual crítica Miquéias faz aos líderes que deveriam conhecer a justiça?",
    "option_a": "Eles reconstruíram Nínive",
    "option_b": "Eles aborreciam o bem e amavam o mal",
    "option_c": "Eles abandonaram a agricultura",
    "option_d": "Eles serviam como sacerdotes fiéis",
    "correct_answer": "B",
    "explanation": "Miquéias 3:1-3 acusa chefes e líderes de odiar o direito e praticar violência contra o povo.",
    "hint": "A crítica é dirigida aos líderes de Israel.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 2,
    "difficulty": "facil",
    "question": "Contra quem é pronunciado o \"ai\" em Miquéias 2:1?",
    "option_a": "Os que maquinam a iniquidade em suas camas",
    "option_b": "As crianças de Judá",
    "option_c": "Os pastores fiéis",
    "option_d": "Os estrangeiros pobres",
    "correct_answer": "A",
    "explanation": "Miquéias 2:1 denuncia os que planejam o mal durante a noite e o praticam pela manhã.",
    "hint": "O planejamento do mal ocorre à noite.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 7,
    "difficulty": "facil",
    "question": "O que Miquéias declara em 7:8 mesmo depois de cair?",
    "option_a": "Fugirei para sempre",
    "option_b": "Desistirei",
    "option_c": "Levantar-me-ei",
    "option_d": "Esconder-me-ei",
    "correct_answer": "C",
    "explanation": "Miquéias 7:8 expressa confiança: ainda que eu caia, levantar-me-ei.",
    "hint": "É uma declaração de esperança e confiança.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 7,
    "difficulty": "medio",
    "question": "Segundo Miquéias 7:19, o que Deus faz com os pecados do seu povo?",
    "option_a": "Reparte-os entre as nações",
    "option_b": "Transforma-os em ouro",
    "option_c": "Lança-os nas profundezas do mar",
    "option_d": "Guarda-os para sempre",
    "correct_answer": "C",
    "explanation": "Miquéias 7:19 descreve o perdão de Deus como lançar os pecados nas profundezas do mar.",
    "hint": "É uma imagem de perdão completo e definitivo.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Em contraste com falsos profetas, do que Miquéias 3:8 diz estar cheio?",
    "option_a": "De sabedoria humana apenas",
    "option_b": "Do poder do Espírito do Senhor",
    "option_c": "De exércitos",
    "option_d": "De riquezas materiais",
    "correct_answer": "B",
    "explanation": "Miquéias 3:8 afirma que o profeta está cheio do poder do Espírito do Senhor, de juízo e de força para denunciar o pecado.",
    "hint": "É uma afirmação de autoridade profética genuína.",
    "source_type": "texto_biblico"
  },
  {
    "book": "miqueias",
    "book_name": "Miquéias",
    "chapter": 1,
    "difficulty": "dificil",
    "question": "Durante o reinado de quais reis de Judá Miquéias profetizou, segundo Miquéias 1:1?",
    "option_a": "Jotão, Acaz e Ezequias",
    "option_b": "Herodes e Augusto",
    "option_c": "Saul, Davi e Salomão",
    "option_d": "Nabucodonosor e Ciro",
    "correct_answer": "A",
    "explanation": "Miquéias 1:1 situa o ministério do profeta nos dias de Jotão, Acaz e Ezequias, reis de Judá.",
    "hint": "São três reis de Judá do período pré-exílico.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Contra qual cidade é dirigida a profecia de Naum?",
    "option_a": "Damasco",
    "option_b": "Tiro",
    "option_c": "Nínive",
    "option_d": "Jerusalém",
    "correct_answer": "C",
    "explanation": "Naum 1:1 apresenta a sentença contra Nínive.",
    "hint": "É a capital assíria.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Como Naum descreve o Senhor em relação à ira?",
    "option_a": "Fraco e indeciso",
    "option_b": "Sempre irado sem misericórdia",
    "option_c": "Tardio em irar-se e grande em poder",
    "option_d": "Indiferente ao mal",
    "correct_answer": "C",
    "explanation": "Naum 1:3 afirma que o Senhor é tardio em irar-se e grande em poder, sem deixar impune o culpado.",
    "hint": "O verso combina paciência e justiça.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 2,
    "difficulty": "medio",
    "question": "Qual imagem aparece na descrição da queda de Nínive?",
    "option_a": "Carros correndo pelas ruas e portas dos rios abertas",
    "option_b": "Uma seca no deserto",
    "option_c": "Um templo sendo reconstruído",
    "option_d": "Um exército chegando de Jerusalém",
    "correct_answer": "A",
    "explanation": "Naum 2 descreve de forma poética o ataque e a queda de Nínive, incluindo carros e a abertura das portas dos rios.",
    "hint": "A cidade está sob ataque.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Por que Nínive é chamada de cidade sanguinária?",
    "option_a": "Por ser pequena",
    "option_b": "Por sua violência, mentira e exploração",
    "option_c": "Por seus muitos jardins",
    "option_d": "Por sua riqueza agrícola",
    "correct_answer": "B",
    "explanation": "Naum 3:1 acusa Nínive de sangue, mentira, roubo e violência.",
    "hint": "A expressão aparece no início do capítulo 3.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 3,
    "difficulty": "dificil",
    "question": "Qual é o destino anunciado para Nínive?",
    "option_a": "Ser reconstruída como capital de Judá",
    "option_b": "Ser destruída e não ter cura para sua ferida",
    "option_c": "Receber um novo templo",
    "option_d": "Governar o Egito",
    "correct_answer": "B",
    "explanation": "Naum 3:7-19 descreve a queda de Nínive como irreversível diante das nações.",
    "hint": "O final do livro não anuncia restauração de Nínive.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Como Naum 1:7 descreve o Senhor para os que confiam nele?",
    "option_a": "Bom e fortaleza no dia da angústia",
    "option_b": "Ausente em tempos de crise",
    "option_c": "Distante e indiferente",
    "option_d": "Fraco diante dos inimigos",
    "correct_answer": "A",
    "explanation": "Naum 1:7 afirma que o Senhor é bom, fortaleza no dia da angústia, e conhece os que nele confiam.",
    "hint": "É um verso de consolo em meio ao anúncio de juízo.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 1,
    "difficulty": "facil",
    "question": "O que Naum 1:15 anuncia que chega sobre os montes?",
    "option_a": "Uma nuvem de gafanhotos",
    "option_b": "Um novo exército assírio",
    "option_c": "Os pés do que anuncia a paz",
    "option_d": "Uma seca prolongada",
    "correct_answer": "C",
    "explanation": "Naum 1:15 anuncia os pés do mensageiro de boas novas, que proclama a paz após a queda de Nínive.",
    "hint": "É uma imagem semelhante à de Isaías 52:7.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 3,
    "difficulty": "medio",
    "question": "A que Nínive é comparada em Naum 3:4 por causa de suas seduções?",
    "option_a": "Uma noiva fiel",
    "option_b": "Uma cidade santa",
    "option_c": "Uma mãe protetora",
    "option_d": "Uma prostituta encantadora e mestra de feitiços",
    "correct_answer": "D",
    "explanation": "Naum 3:4 acusa Nínive de seduzir nações como uma prostituta encantadora, mestra de feitiçarias.",
    "hint": "A acusação envolve sedução e engano.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 2,
    "difficulty": "medio",
    "question": "A que Nínive é comparada em Naum 2:11-12, por causa de sua violência conquistadora?",
    "option_a": "Um templo sagrado",
    "option_b": "Um covil de leões",
    "option_c": "Uma torre pacífica",
    "option_d": "Um jardim florido",
    "correct_answer": "B",
    "explanation": "Naum 2:11-12 compara Nínive a um covil de leões, cheio de presas, símbolo de sua violência contra outras nações.",
    "hint": "É uma comparação com um animal predador feroz.",
    "source_type": "texto_biblico"
  },
  {
    "book": "naum",
    "book_name": "Naum",
    "chapter": 1,
    "difficulty": "dificil",
    "question": "O que Deus decreta contra a descendência do rei assírio em Naum 1:14?",
    "option_a": "Que reconstruiria o templo de Jerusalém",
    "option_b": "Que se tornaria aliado de Judá",
    "option_c": "Que seria coroado rei universal",
    "option_d": "Que seu nome não teria mais descendência",
    "correct_answer": "D",
    "explanation": "Naum 1:14 anuncia que do nome do rei assírio não haveria mais semeadura, e os ídolos de sua casa seriam destruídos.",
    "hint": "Envolve o fim da linhagem e dos ídolos do rei.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 1,
    "difficulty": "facil",
    "question": "O que Habacuque faz principalmente no início do livro?",
    "option_a": "Interpreta sonhos de Nabucodonosor",
    "option_b": "Foge para o Egito",
    "option_c": "Questiona a Deus sobre a violência e a injustiça",
    "option_d": "Constrói um altar",
    "correct_answer": "C",
    "explanation": "Habacuque começa apresentando perguntas e queixas sobre a violência e a aparente demora da justiça.",
    "hint": "O livro tem forma de diálogo entre profeta e Deus.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 2,
    "difficulty": "facil",
    "question": "Qual frase famosa aparece em Habacuque 2:4?",
    "option_a": "O Senhor é meu pastor",
    "option_b": "Tudo é vaidade",
    "option_c": "O justo viverá pela sua fé",
    "option_d": "Olho por olho",
    "correct_answer": "C",
    "explanation": "Habacuque 2:4 afirma: o justo viverá pela sua fé/fidelidade, conforme a tradução.",
    "hint": "É uma frase central do livro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 2,
    "difficulty": "medio",
    "question": "O que Deus manda Habacuque fazer com a visão?",
    "option_a": "Escrevê-la claramente em tábuas",
    "option_b": "Entregá-la ao rei do Egito",
    "option_c": "Apagá-la",
    "option_d": "Escondê-la",
    "correct_answer": "A",
    "explanation": "Habacuque 2:2 ordena que a visão seja escrita claramente em tábuas para que possa ser lida.",
    "hint": "A instrução é escrever a visão.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Apesar da crise, como termina a oração de Habacuque?",
    "option_a": "Com silêncio absoluto",
    "option_b": "Com alegria e confiança em Deus",
    "option_c": "Com uma coroação",
    "option_d": "Com uma fuga",
    "correct_answer": "B",
    "explanation": "Habacuque 3:17-19 reconhece a falta de frutos e rebanhos, mas afirma alegria no Senhor e confiança em Deus.",
    "hint": "A alegria não depende da prosperidade.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 1,
    "difficulty": "dificil",
    "question": "Qual povo Deus diz que levantará como instrumento de juízo?",
    "option_a": "Os filisteus",
    "option_b": "Os caldeus",
    "option_c": "Os egípcios",
    "option_d": "Os edomitas",
    "correct_answer": "B",
    "explanation": "Habacuque 1:6 identifica os caldeus como povo que Deus levantaria para executar juízo.",
    "hint": "Caldeus é uma designação associada aos babilônios.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Como começa o lamento de Habacuque no capítulo 1?",
    "option_a": "Eis que o rei chegou vitorioso",
    "option_b": "O templo está reconstruído",
    "option_c": "Louvado seja o Senhor para sempre",
    "option_d": "Até quando, Senhor, clamarei e tu não ouvirás?",
    "correct_answer": "D",
    "explanation": "Habacuque 1:2 abre o livro com uma queixa sobre a violência e a aparente demora da resposta de Deus.",
    "hint": "É uma pergunta sobre o tempo de espera.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 3,
    "difficulty": "facil",
    "question": "Com que imagem de força Habacuque 3:19 termina o livro?",
    "option_a": "Uma frota poderosa",
    "option_b": "Um exército invencível",
    "option_c": "Um novo templo de ouro",
    "option_d": "Pés como os das cervas, andando nas alturas",
    "correct_answer": "D",
    "explanation": "Habacuque 3:19 declara que o Senhor é sua força e faz seus pés como os da cerva, capazes de andar sobre as alturas.",
    "hint": "É uma comparação com um animal ágil em terrenos altos.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 2,
    "difficulty": "medio",
    "question": "O que Habacuque 2:14 promete que encherá a terra?",
    "option_a": "As águas do dilúvio",
    "option_b": "O ouro das nações",
    "option_c": "O conhecimento da glória do Senhor",
    "option_d": "Os exércitos da Babilônia",
    "correct_answer": "C",
    "explanation": "Habacuque 2:14 promete que a terra se encherá do conhecimento da glória do Senhor, como as águas cobrem o mar.",
    "hint": "É uma imagem de plenitude comparada à água do mar.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 2,
    "difficulty": "medio",
    "question": "Quantos \"ais\" (pronunciamentos de juízo) Habacuque declara contra o opressor no capítulo 2?",
    "option_a": "Nenhum",
    "option_b": "Dez",
    "option_c": "Dois",
    "option_d": "Cinco",
    "correct_answer": "D",
    "explanation": "Habacuque 2:6-19 registra cinco declarações de \"ai\" contra a injustiça e a opressão do conquistador.",
    "hint": "É uma série de acusações repetidas com a mesma palavra.",
    "source_type": "texto_biblico"
  },
  {
    "book": "habacuque",
    "book_name": "Habacuque",
    "chapter": 1,
    "difficulty": "dificil",
    "question": "Na segunda queixa de Habacuque (cap. 1), o que o incomoda sobre o uso dos caldeus por Deus?",
    "option_a": "Que Deus use um povo mais ímpio para julgar um povo menos ímpio",
    "option_b": "Que os caldeus sejam pobres",
    "option_c": "Que os caldeus adorem o Deus de Israel",
    "option_d": "Que os caldeus nunca vençam guerras",
    "correct_answer": "A",
    "explanation": "Habacuque 1:12-13 questiona como Deus, de olhos puros, pode usar os caldeus, mais perversos, para punir um povo menos ímpio.",
    "hint": "É um questionamento sobre a justiça divina usando um instrumento moralmente pior.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Quem é identificado como pai de Sofonias?",
    "option_a": "Amós",
    "option_b": "Ezequias",
    "option_c": "Cusi",
    "option_d": "Hulda",
    "correct_answer": "C",
    "explanation": "Sofonias 1:1 começa com a genealogia e identifica Sofonias como filho de Cusi.",
    "hint": "O nome aparece no primeiro versículo.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual expressão marca o anúncio de juízo em Sofonias?",
    "option_a": "A festa das colheitas",
    "option_b": "O ano do jubileu",
    "option_c": "O dia do Senhor",
    "option_d": "A noite do rei",
    "correct_answer": "C",
    "explanation": "O livro repete a expressão dia do Senhor como momento de juízo.",
    "hint": "É o tema temporal mais destacado.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 2,
    "difficulty": "medio",
    "question": "O que Sofonias 2:3 recomenda buscar?",
    "option_a": "O Senhor, a justiça e a humildade",
    "option_b": "Riquezas e poder",
    "option_c": "A Assíria",
    "option_d": "Um novo palácio",
    "correct_answer": "A",
    "explanation": "Sofonias 2:3 chama os humildes da terra a buscar o Senhor, a justiça e a humildade.",
    "hint": "São três elementos no convite.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 3,
    "difficulty": "medio",
    "question": "Como termina o livro de Sofonias?",
    "option_a": "Com a queda de Jerusalém sem esperança",
    "option_b": "Com uma guerra no Egito",
    "option_c": "Com promessa de restauração e alegria de Deus sobre seu povo",
    "option_d": "Com a morte do profeta",
    "correct_answer": "C",
    "explanation": "Sofonias 3:14-20 termina com restauração, reunião dos dispersos e alegria associada à presença de Deus no meio do povo.",
    "hint": "O final muda do juízo para a restauração.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 3,
    "difficulty": "dificil",
    "question": "Qual cidade é mencionada entre os alvos de juízo no livro?",
    "option_a": "Hebrom",
    "option_b": "Nínive",
    "option_c": "Belém",
    "option_d": "Damasco",
    "correct_answer": "B",
    "explanation": "Sofonias 2:13-15 anuncia juízo contra a Assíria e Nínive, descrita como cidade desolada.",
    "hint": "A cidade assíria aparece explicitamente no capítulo 2.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual é a extensão do juízo anunciado logo no início de Sofonias 1:2-3?",
    "option_a": "Destruição total sobre homens, animais, aves e peixes",
    "option_b": "Apenas sobre os sacerdotes",
    "option_c": "Apenas sobre os estrangeiros",
    "option_d": "Somente sobre a Assíria",
    "correct_answer": "A",
    "explanation": "Sofonias 1:2-3 anuncia uma destruição abrangente sobre toda a face da terra, incluindo homens e animais.",
    "hint": "É uma linguagem de juízo cósmico e abrangente.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 3,
    "difficulty": "facil",
    "question": "O que o Senhor faz por seu povo com alegria, segundo Sofonias 3:17?",
    "option_a": "Os pune sem misericórdia",
    "option_b": "Os envia ao exílio",
    "option_c": "Os abandona no deserto",
    "option_d": "Canta sobre eles com júbilo",
    "correct_answer": "D",
    "explanation": "Sofonias 3:17 descreve Deus se alegrando e cantando sobre seu povo com júbilo, uma imagem terna do amor divino.",
    "hint": "É uma imagem de alegria e canto de Deus.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 1,
    "difficulty": "medio",
    "question": "Com o que Sofonias 1:12 compara os que estavam acomodados espiritualmente?",
    "option_a": "Pão fresco",
    "option_b": "Água corrente e pura",
    "option_c": "Ouro refinado",
    "option_d": "Vinho parado sobre as fezes (borra)",
    "correct_answer": "D",
    "explanation": "Sofonias 1:12 fala de buscar com lanternas os que estão acomodados como vinho sobre a borra, indiferentes ao Senhor.",
    "hint": "É uma imagem de estagnação e indiferença espiritual.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 2,
    "difficulty": "medio",
    "question": "Quais grupos de nações são alvo dos oráculos de juízo em Sofonias 2?",
    "option_a": "Filístia, Moabe, Amom, Cuxe e Assíria",
    "option_b": "Somente as tribos de Israel",
    "option_c": "Apenas o Egito",
    "option_d": "Apenas Roma e Grécia",
    "correct_answer": "A",
    "explanation": "Sofonias 2 traz oráculos de juízo contra Filístia, Moabe, Amom, Cuxe (Etiópia) e a Assíria.",
    "hint": "São nações vizinhas de Judá, incluindo a grande potência assíria.",
    "source_type": "texto_biblico"
  },
  {
    "book": "sofonias",
    "book_name": "Sofonias",
    "chapter": 1,
    "difficulty": "dificil",
    "question": "Segundo a genealogia em Sofonias 1:1, o profeta é apresentado como descendente de qual rei de Judá?",
    "option_a": "Davi",
    "option_b": "Ezequias",
    "option_c": "Josias, seu contemporâneo",
    "option_d": "Salomão",
    "correct_answer": "B",
    "explanation": "Sofonias 1:1 traça a genealogia do profeta até Ezequias, sugerindo possível ascendência real.",
    "hint": "É um rei reformador anterior a Josias.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual obra Ageu incentiva o povo a retomar?",
    "option_a": "O palácio do rei",
    "option_b": "A reconstrução do templo",
    "option_c": "A muralha de Jericó",
    "option_d": "A construção de uma frota",
    "correct_answer": "B",
    "explanation": "Ageu 1:8 chama o povo a subir ao monte, trazer madeira e edificar a casa de Deus.",
    "hint": "O templo é chamado de casa do Senhor.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Quem governava Judá como governador no contexto de Ageu?",
    "option_a": "Zorobabel",
    "option_b": "Saul",
    "option_c": "Elias",
    "option_d": "Ezequias",
    "correct_answer": "A",
    "explanation": "Ageu 1:1 identifica Zorobabel, filho de Sealtiel, como governador de Judá.",
    "hint": "Ele aparece ao lado de Josué, o sumo sacerdote.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 1,
    "difficulty": "medio",
    "question": "Quem era o sumo sacerdote mencionado junto a Zorobabel?",
    "option_a": "Josué, filho de Jeozadaque",
    "option_b": "Zadoque",
    "option_c": "Arão",
    "option_d": "Eli",
    "correct_answer": "A",
    "explanation": "Ageu 1:1 e outros textos do livro mencionam Josué, filho de Jeozadaque, como sumo sacerdote.",
    "hint": "Não é Josué, sucessor de Moisés.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 2,
    "difficulty": "medio",
    "question": "O que Deus promete em Ageu 2:9 sobre a glória da casa?",
    "option_a": "Não haveria templo",
    "option_b": "A casa seria abandonada",
    "option_c": "A glória desta última casa seria maior que a da primeira",
    "option_d": "O templo seria transferido para o Egito",
    "correct_answer": "C",
    "explanation": "Ageu 2:9 promete que a glória desta última casa seria maior que a primeira e anuncia paz.",
    "hint": "A comparação é entre a casa anterior e a reconstruída.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 2,
    "difficulty": "dificil",
    "question": "Qual imagem política aparece em Ageu 2:22?",
    "option_a": "A Assíria voltará a governar",
    "option_b": "Zorobabel será coroado rei de todas as nações",
    "option_c": "Tronos serão derrubados e reinos serão destruídos",
    "option_d": "Israel dominará o Egito imediatamente",
    "correct_answer": "C",
    "explanation": "Ageu 2:22 fala em derrubar tronos e destruir forças de reinos, dentro da mensagem escatológica do profeta.",
    "hint": "A linguagem é de abalo dos poderes políticos.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 1,
    "difficulty": "facil",
    "question": "O que Ageu 1:6 diz sobre o salário de quem trabalhava enquanto negligenciava o templo?",
    "option_a": "Dobrava a cada semana",
    "option_b": "Era guardado com segurança",
    "option_c": "Era posto num saco furado",
    "option_d": "Vinha do Egito",
    "correct_answer": "C",
    "explanation": "Ageu 1:6 descreve a futilidade econômica do povo, comparando o salário a algo posto num saco furado.",
    "hint": "É uma imagem de perda constante e frustração.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 1,
    "difficulty": "facil",
    "question": "O que Deus declarou ao povo depois que eles obedeceram e começaram a reconstrução, segundo Ageu 1:13?",
    "option_a": "Esquecerei o templo",
    "option_b": "Eu sou convosco",
    "option_c": "Eu vos abandono",
    "option_d": "Não voltarei mais",
    "correct_answer": "B",
    "explanation": "Ageu 1:13 registra a palavra de encorajamento do Senhor: Eu sou convosco, diz o Senhor.",
    "hint": "É uma promessa de presença divina.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 2,
    "difficulty": "medio",
    "question": "O que Ageu 2:7 anuncia que virá depois que Deus abalar céus e terra?",
    "option_a": "Um novo dilúvio",
    "option_b": "A queda definitiva de Jerusalém",
    "option_c": "O fim dos sacrifícios",
    "option_d": "O Desejado de todas as nações",
    "correct_answer": "D",
    "explanation": "Ageu 2:6-7 anuncia o abalo dos céus e da terra, seguido da vinda do Desejado de todas as nações, enchendo a casa de glória.",
    "hint": "É uma expressão messiânica sobre expectativa das nações.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 1,
    "difficulty": "medio",
    "question": "Segundo Ageu 1:14, o que o Senhor despertou em Zorobabel, Josué e no povo?",
    "option_a": "O desejo de fugir para o Egito",
    "option_b": "O espírito para trabalharem na casa do Senhor",
    "option_c": "O interesse em construir palácios pessoais",
    "option_d": "A vontade de abandonar Judá",
    "correct_answer": "B",
    "explanation": "Ageu 1:14 relata que o Senhor despertou o espírito de Zorobabel, Josué e do restante do povo para a obra da reconstrução.",
    "hint": "É um despertar coletivo para o trabalho no templo.",
    "source_type": "texto_biblico"
  },
  {
    "book": "ageu",
    "book_name": "Ageu",
    "chapter": 2,
    "difficulty": "dificil",
    "question": "No versículo final de Ageu (2:23), a que objeto de honra Deus compara Zorobabel?",
    "option_a": "Uma espada real",
    "option_b": "Uma coroa de ouro",
    "option_c": "Um cetro de ferro",
    "option_d": "Um anel de selar",
    "correct_answer": "D",
    "explanation": "Ageu 2:23 declara que Deus fará de Zorobabel, seu servo, como um anel de selar, símbolo de honra e escolha divina.",
    "hint": "É um objeto usado para autenticar documentos com um selo pessoal.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual era a principal mensagem inicial de Zacarias 1:3?",
    "option_a": "Fugi para o Egito",
    "option_b": "Voltai para mim, e eu me voltarei para vós",
    "option_c": "Escolham outro rei",
    "option_d": "Não construam o templo",
    "correct_answer": "B",
    "explanation": "Zacarias 1:3 chama o povo a retornar ao Senhor e promete que o Senhor se voltará para eles.",
    "hint": "É um chamado ao retorno.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 5,
    "difficulty": "facil",
    "question": "O que Zacarias vê em uma das visões do capítulo 5?",
    "option_a": "Um peixe gigante",
    "option_b": "Uma arca de Noé",
    "option_c": "Uma coroa de ferro",
    "option_d": "Um rolo voante",
    "correct_answer": "D",
    "explanation": "Zacarias 5:1 descreve um rolo voante.",
    "hint": "É uma visão escrita e voadora.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 4,
    "difficulty": "medio",
    "question": "Na visão do capítulo 4, o que representa o azeite em relação às duas oliveiras?",
    "option_a": "A riqueza do rei",
    "option_b": "A força militar",
    "option_c": "A água do templo",
    "option_d": "A provisão do Espírito de Deus",
    "correct_answer": "D",
    "explanation": "Zacarias 4 enfatiza a ação do Espírito: não por força nem por poder, mas pelo Espírito do Senhor.",
    "hint": "O verso 6 fornece a chave da visão.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 9,
    "difficulty": "medio",
    "question": "Qual rei é descrito chegando a Jerusalém montado em um jumento?",
    "option_a": "O rei da Assíria",
    "option_b": "Um rei justo e salvador",
    "option_c": "O faraó do Egito",
    "option_d": "Nabucodonosor",
    "correct_answer": "B",
    "explanation": "Zacarias 9:9 descreve um rei justo, salvador e humilde, montado em jumento.",
    "hint": "A descrição é de um rei humilde.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 12,
    "difficulty": "dificil",
    "question": "Qual expressão aparece em Zacarias 12:10 sobre o futuro arrependimento?",
    "option_a": "Jerusalém será abandonada para sempre",
    "option_b": "Israel será levado ao Egito",
    "option_c": "Olharão para aquele a quem traspassaram e prantearão",
    "option_d": "Não haverá arrependimento",
    "correct_answer": "C",
    "explanation": "Zacarias 12:10 descreve derramamento de espírito de graça e súplicas, seguido de lamento ao olhar para aquele que foi traspassado.",
    "hint": "É uma passagem de lamento e arrependimento.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 3,
    "difficulty": "facil",
    "question": "Na visão de Zacarias 3, quem acusa o sumo sacerdote Josué diante do anjo do Senhor?",
    "option_a": "O rei da Babilônia",
    "option_b": "Satanás",
    "option_c": "Um sacerdote rival",
    "option_d": "Um profeta falso",
    "correct_answer": "B",
    "explanation": "Zacarias 3:1 descreve Satanás à direita de Josué, o sumo sacerdote, para acusá-lo, mas o Senhor o repreende.",
    "hint": "É o acusador por excelência nas Escrituras.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 6,
    "difficulty": "facil",
    "question": "O que Zacarias vê saindo dentre dois montes de bronze na visão do capítulo 6?",
    "option_a": "Uma nuvem de fogo apenas",
    "option_b": "Um exército de anjos armados",
    "option_c": "Quatro carros puxados por cavalos",
    "option_d": "Uma frota de navios",
    "correct_answer": "C",
    "explanation": "Zacarias 6:1-8 descreve quatro carros com cavalos de cores diferentes, representando os quatro espíritos dos céus.",
    "hint": "São veículos puxados por cavalos de cores distintas.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 8,
    "difficulty": "medio",
    "question": "Segundo Zacarias 8:23, o que dez homens de todas as línguas farão a um judeu?",
    "option_a": "Tomarão pela orla de sua veste, dizendo que irão com ele",
    "option_b": "Pedirão para adorar outros deuses",
    "option_c": "Ignorarão completamente",
    "option_d": "Expulsarão da cidade",
    "correct_answer": "A",
    "explanation": "Zacarias 8:23 anuncia que nações desejarão acompanhar o povo judeu, pois reconhecerão que Deus está com eles.",
    "hint": "Envolve reconhecimento da presença de Deus com o povo.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 11,
    "difficulty": "medio",
    "question": "Por quantas moedas de prata o pastor (representando o Senhor) foi avaliado em Zacarias 11:12?",
    "option_a": "Trinta",
    "option_b": "Cem",
    "option_c": "Mil",
    "option_d": "Dez",
    "correct_answer": "A",
    "explanation": "Zacarias 11:12-13 menciona trinta moedas de prata, valor depois associado à traição de Judas contra Jesus.",
    "hint": "É o mesmo valor pago pela traição de Judas no Novo Testamento.",
    "source_type": "texto_biblico"
  },
  {
    "book": "zacarias",
    "book_name": "Zacarias",
    "chapter": 14,
    "difficulty": "dificil",
    "question": "Em Zacarias 14:4, onde os pés do Senhor se firmarão, fazendo o monte se fender em duas partes?",
    "option_a": "Monte Sinai",
    "option_b": "Monte Carmelo",
    "option_c": "Monte Nebo",
    "option_d": "Monte das Oliveiras",
    "correct_answer": "D",
    "explanation": "Zacarias 14:4 descreve os pés do Senhor firmados no monte das Oliveiras, que se fenderá ao meio no dia do Senhor.",
    "hint": "É o monte a leste de Jerusalém.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Qual é a primeira pergunta de contestação registrada no diálogo de Malaquias?",
    "option_a": "Quem é o rei?",
    "option_b": "Quando virá Elias?",
    "option_c": "Onde está Moisés?",
    "option_d": "Em que nos amaste?",
    "correct_answer": "D",
    "explanation": "Malaquias 1:2 registra a pergunta do povo: em que nos amaste?",
    "hint": "Ela vem logo após Deus declarar seu amor por Jacó.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 3,
    "difficulty": "facil",
    "question": "Quem é prometido como mensageiro antes da chegada do Senhor?",
    "option_a": "Um general romano",
    "option_b": "Um mensageiro que prepararia o caminho",
    "option_c": "Um novo rei assírio",
    "option_d": "Um sacerdote de Samaria",
    "correct_answer": "B",
    "explanation": "Malaquias 3:1 fala do mensageiro que preparará o caminho diante do Senhor.",
    "hint": "A palavra-chave é mensageiro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 3,
    "difficulty": "medio",
    "question": "O que Malaquias 3:10 relaciona ao dízimo?",
    "option_a": "Trazer todos os dízimos à casa do tesouro",
    "option_b": "Usar o dízimo para guerra",
    "option_c": "Entregar somente ao rei",
    "option_d": "Guardar o dízimo em casa",
    "correct_answer": "A",
    "explanation": "Malaquias 3:10 chama a trazer todos os dízimos à casa do tesouro e apresenta a promessa de provisão.",
    "hint": "A expressão é casa do tesouro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 4,
    "difficulty": "medio",
    "question": "O que o final do livro de Malaquias promete enviar antes do grande e terrível dia do Senhor?",
    "option_a": "Jeremias",
    "option_b": "Samuel",
    "option_c": "Elias, o profeta",
    "option_d": "Natã",
    "correct_answer": "C",
    "explanation": "Malaquias 4:5 promete enviar Elias, o profeta, antes do grande e terrível dia do Senhor.",
    "hint": "É o último nome mencionado no livro.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 2,
    "difficulty": "dificil",
    "question": "Qual problema dos sacerdotes é denunciado em Malaquias 2?",
    "option_a": "Desprezavam o nome de Deus e ofereciam sacrifícios inadequados",
    "option_b": "Não conheciam a Lei de Moisés",
    "option_c": "Construíam muitos altares",
    "option_d": "Recusavam-se a trabalhar no templo",
    "correct_answer": "A",
    "explanation": "Malaquias 1–2 denuncia sacerdotes que desprezavam o nome de Deus e aceitavam animais inadequados para sacrifício.",
    "hint": "A denúncia envolve a qualidade das ofertas.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 1,
    "difficulty": "facil",
    "question": "Que tipo de animais o povo oferecia indevidamente em sacrifício, segundo Malaquias 1:8?",
    "option_a": "Apenas aves selvagens",
    "option_b": "Cegos, coxos e enfermos",
    "option_c": "Peixes do rio Jordão",
    "option_d": "Somente animais gordos e perfeitos",
    "correct_answer": "B",
    "explanation": "Malaquias 1:8 repreende o povo por oferecer animais cegos, coxos e enfermos, desonrando a Deus.",
    "hint": "São animais com defeitos físicos.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 2,
    "difficulty": "facil",
    "question": "O que Malaquias 2:16 diz que o Senhor aborrece?",
    "option_a": "As orações longas",
    "option_b": "Os dízimos",
    "option_c": "Os sacrifícios de louvor",
    "option_d": "O repúdio (divórcio)",
    "correct_answer": "D",
    "explanation": "Malaquias 2:16 declara que o Senhor Deus de Israel aborrece o repúdio, condenando a infidelidade conjugal.",
    "hint": "É relacionado à quebra do casamento.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 3,
    "difficulty": "medio",
    "question": "O que Malaquias 3:6 afirma sobre o caráter de Deus que garante que Israel não foi consumido?",
    "option_a": "Eu esqueço facilmente",
    "option_b": "Eu mudo conforme as nações",
    "option_c": "Eu abandono meu povo",
    "option_d": "Eu, o Senhor, não mudo",
    "correct_answer": "D",
    "explanation": "Malaquias 3:6 afirma a imutabilidade de Deus como razão pela qual os filhos de Jacó não foram consumidos.",
    "hint": "É uma afirmação sobre a constância do caráter divino.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 3,
    "difficulty": "medio",
    "question": "De que forma Malaquias 3:8 diz que o povo estava roubando a Deus?",
    "option_a": "Nos sacrifícios de animais",
    "option_b": "Nas orações públicas",
    "option_c": "Nos dízimos e nas ofertas",
    "option_d": "Na construção do templo",
    "correct_answer": "C",
    "explanation": "Malaquias 3:8 acusa o povo de roubar a Deus retendo dízimos e ofertas.",
    "hint": "Está ligado à contribuição financeira ao templo.",
    "source_type": "texto_biblico"
  },
  {
    "book": "malaquias",
    "book_name": "Malaquias",
    "chapter": 2,
    "difficulty": "dificil",
    "question": "Qual argumento de unidade Malaquias 2:10 usa para repreender a traição entre irmãos?",
    "option_a": "Não somos todos sacerdotes?",
    "option_b": "Não temos todos um mesmo Pai e um mesmo Criador?",
    "option_c": "Não vivemos todos no Egito?",
    "option_d": "Não somos todos reis?",
    "correct_answer": "B",
    "explanation": "Malaquias 2:10 apela à paternidade comum de Deus para denunciar a deslealdade entre os israelitas, quebrando a aliança dos pais.",
    "hint": "É um apelo à origem e criação comuns.",
    "source_type": "texto_biblico"
  }
].map((q,i)=>({id:uuid(i+1),...q,order_index:i+1,active:true}));
export const ACHIEVEMENTS=[
{id:'11111111-1111-4111-8111-111111111111',code:'FIRST_GAME',name:'Primeira Partida',icon:'🎯',description:'Complete sua primeira partida.',criteria:{type:'attempts_count',value:1}},
{id:'11111111-1111-4111-8111-111111111112',code:'FIVE_GAMES',name:'5 Partidas',icon:'🔥',description:'Complete 5 partidas.',criteria:{type:'attempts_count',value:5}},
{id:'11111111-1111-4111-8111-111111111113',code:'TEN_GAMES',name:'10 Partidas',icon:'⚡',description:'Complete 10 partidas.',criteria:{type:'attempts_count',value:10}},
{id:'11111111-1111-4111-8111-111111111114',code:'PERFECT_SCORE',name:'100% de Acertos',icon:'💯',description:'Termine uma partida com todas as respostas corretas.',criteria:{type:'perfect_attempt',value:true}},
{id:'11111111-1111-4111-8111-111111111115',code:'TOP_TEN',name:'Top 10',icon:'🏅',description:'Entre no top 10 do ranking geral.',criteria:{type:'leaderboard_position',value:10}},
{id:'11111111-1111-4111-8111-111111111116',code:'FIRST_PLACE',name:'1º Lugar',icon:'👑',description:'Alcance o 1º lugar do ranking geral.',criteria:{type:'leaderboard_position',value:1}},
{id:'11111111-1111-4111-8111-111111111117',code:'PROPHETS_EXPERT',name:'Especialista nos Profetas',icon:'📖',description:'Acumule 100 respostas corretas e alcance 85% ou mais de acerto.',criteria:{type:'expert',correct:100,min_accuracy:85}}];
export default {PROPHETS,QUESTIONS,ACHIEVEMENTS};
