-- ============================================================================
--  Migração: ampliar o banco de 60 para 120 perguntas (10 por profeta)
-- ----------------------------------------------------------------------------
--  Adiciona 5 novas perguntas para cada um dos 12 profetas menores, sem
--  remover ou alterar as 60 perguntas originais. Idempotente: pode ser
--  executada mais de uma vez sem duplicar linhas (checa pelo texto da
--  pergunta antes de inserir).
--  Uso: rode este script no SQL Editor do Supabase em bancos que já tenham
--  sido criados com o seed antigo (60 perguntas).
-- ============================================================================

insert into public.questions
(book,book_name,chapter,question,difficulty,option_a,option_b,option_c,option_d,correct_answer,explanation,hint,source_type,order_index)
select v.book, v.book_name, v.chapter, v.question, v.difficulty::question_difficulty, v.option_a, v.option_b, v.option_c, v.option_d,
       v.correct_answer::answer_letter, v.explanation, v.hint, v.source_type, v.order_index
from (values
('oseias','Oséias',3,'O que Oséias fez para readquirir sua esposa, ilustrando o amor redentor de Deus?','facil','Pagou com prata e cevada','Foi a um tribunal romano','Pediu ajuda ao rei da Assíria','Construiu um novo templo','A','Oséias 3:2 relata que o profeta comprou sua esposa por quinze moedas de prata e certa quantidade de cevada, simbolizando a redenção de Israel.','O preço envolve dinheiro e um grão.','texto_biblico',6),
('oseias','Oséias',4,'Qual acusação abre a controvérsia de Deus com Israel em Oséias 4?','facil','Não há conhecimento de Deus na terra','O povo é rico demais','O templo foi destruído','O rei foi deposto','A','Oséias 4:1 acusa a terra de faltar verdade, misericórdia e conhecimento de Deus.','É uma falta de relacionamento com Deus.','texto_biblico',7),
('oseias','Oséias',13,'Qual pergunta desafiadora sobre a morte aparece em Oséias 13:14?','medio','Onde está, ó morte, o teu aguilhão?','Quando virá o novo rei?','Onde está a arca da aliança?','Quem construirá o templo?','A','Oséias 13:14 desafia a morte e o Seol, texto depois citado em 1 Coríntios 15.','É citado no Novo Testamento sobre a ressurreição.','texto_biblico',8),
('oseias','Oséias',10,'O que Oséias 10:12 convida o povo a semear?','medio','Justiça','Ouro','Discórdia','Medo','A','Oséias 10:12 exorta: semeai para vós a justiça e colhei segundo a bondade.','É um chamado agrícola com sentido moral.','texto_biblico',9),
('oseias','Oséias',5,'Em Oséias 5:15, o que Deus diz que fará até que o povo reconheça sua culpa?','dificil','Voltará ao seu lugar','Destruirá o mundo','Abandonará os profetas','Enviará outro dilúvio','A','Oséias 5:15 apresenta Deus retirando-se até que o povo, em angústia, busque a sua face.','Deus se retira temporariamente.','texto_biblico',10),
('joel','Joel',1,'Quem Joel convoca a despertar e chorar por causa da devastação em Joel 1:5?','facil','Os bêbados','Os sacerdotes apenas','Os reis estrangeiros','Os exércitos vizinhos','A','Joel 1:5 chama os bêbados a despertarem e chorarem pela perda do vinho novo.','Estão associados à bebida.','texto_biblico',16),
('joel','Joel',2,'O que o povo deve tocar em Sião para anunciar o perigo em Joel 2:1?','facil','A trombeta','O tambor','A harpa','Os címbalos','A','Joel 2:1 ordena tocar a trombeta em Sião para soar o alarme.','É um instrumento de alerta.','texto_biblico',17),
('joel','Joel',2,'O que Deus promete restituir em Joel 2:25?','medio','Os anos que o gafanhoto comeu','As muralhas da cidade','Os tronos derrubados','As tribos perdidas','A','Joel 2:25 promete restituir os anos devorados pelo gafanhoto, símbolo de restauração após o juízo.','É uma promessa de compensação pelo tempo perdido.','texto_biblico',18),
('joel','Joel',3,'Em Joel 3:10, o que as nações são chamadas a transformar em espadas?','medio','As relhas dos seus arados','Seus templos','Seus rebanhos','Suas tendas','A','Joel 3:10 inverte a imagem de paz (vista em Miquéias e Isaías), convocando as nações à guerra: batei as relhas em espadas.','É o oposto da imagem de paz de Miquéias 4:3.','texto_biblico',19),
('joel','Joel',2,'Segundo Joel 2:32, o que acontecerá a todo aquele que invocar o nome do Senhor?','dificil','Será salvo','Será exilado','Perderá seus bens','Será esquecido','A','Joel 2:32 promete que todo aquele que invocar o nome do Senhor será salvo, texto citado em Atos 2 e Romanos 10.','É citado por Pedro no dia de Pentecostes.','texto_biblico',20),
('amos','Amós',4,'Como Amós 4:1 chama as mulheres opressoras de Samaria?','facil','Vacas de Basã','Pombas do vale','Leoas do deserto','Águias da montanha','A','Amós 4:1 usa a expressão vacas de Basã para denunciar mulheres que oprimiam os pobres.','É uma comparação com um animal de pastagem rica.','texto_biblico',26),
('amos','Amós',9,'O que Deus promete restaurar em Amós 9:11?','facil','O tabernáculo caído de Davi','O palácio do Egito','A muralha de Nínive','O templo de Baal','A','Amós 9:11 promete levantar o tabernáculo caído de Davi, texto citado em Atos 15.','É uma promessa messiânica ligada à linhagem de Davi.','texto_biblico',27),
('amos','Amós',2,'Do que Israel é acusado em Amós 2:6, ao vender pessoas?','medio','Vender o justo por prata e o pobre por um par de sandálias','Vender terras para o Egito','Vender animais sagrados','Vender armas para a Assíria','A','Amós 2:6 denuncia a venda do justo por dinheiro e do pobre por um simples par de sandálias.','É uma denúncia de injustiça social extrema.','texto_biblico',28),
('amos','Amós',6,'Contra quem é o "ai" pronunciado em Amós 6:1?','medio','Os que vivem sossegados em Sião','Os pastores humildes','Os estrangeiros pobres','Os sacerdotes fiéis','A','Amós 6:1 pronuncia ai sobre os que vivem despreocupados e confiantes em Sião e em Samaria.','É uma crítica à complacência dos líderes.','texto_biblico',29),
('amos','Amós',7,'Quem ordenou que Amós fugisse para Judá e parasse de profetizar em Betel?','dificil','Amazias, sacerdote de Betel','O rei da Assíria','Jeroboão pessoalmente','Um profeta rival','A','Amós 7:10-13 narra o confronto com Amazias, sacerdote de Betel, que expulsou Amós, ao que o profeta respondeu que não era profeta profissional, mas pastor chamado por Deus.','É o sacerdote do santuário real de Betel.','texto_biblico',30),
('obadias','Obadias',1,'Segundo Obadias 3, o que enganou o coração de Edom?','facil','A soberba','A pobreza','A ignorância','A fome','A','Obadias 3 diz que a soberba do coração de Edom o enganou, confiando em sua posição elevada nas rochas.','É um pecado ligado ao orgulho.','texto_biblico',36),
('obadias','Obadias',1,'Onde Edom habitava, segundo a descrição de Obadias 3?','facil','Nas fendas das rochas, em lugar alto','Em barcos no mar Vermelho','Em tendas no deserto do Sinai','Nas margens do rio Nilo','A','Obadias 3 descreve Edom habitando nas fendas das rochas, confiante em sua altura e segurança.','É uma região montanhosa e fortificada.','texto_biblico',37),
('obadias','Obadias',1,'Qual foi a atitude de Edom quando estrangeiros saquearam Jerusalém, segundo Obadias 11?','medio','Ficou de lado e se comportou como um deles','Defendeu Jerusalém com seu exército','Avisou os profetas com antecedência','Abrigou os refugiados de Judá','A','Obadias 11 acusa Edom de ficar de lado, omisso, comportando-se como um dos invasores.','A culpa envolve omissão e cumplicidade.','texto_biblico',38),
('obadias','Obadias',1,'Qual princípio de reciprocidade aparece em Obadias 15?','medio','Como fizeste, se fará a ti','Quem semeia pouco colhe muito','O rico sempre vencerá','Não haverá julgamento para nenhuma nação','A','Obadias 15 anuncia que o dia do Senhor virá sobre todas as nações e o que Edom fez lhe será retribuído.','É uma lei de causa e efeito no juízo divino.','texto_biblico',39),
('obadias','Obadias',1,'Em Obadias 18, a que a casa de Esaú é comparada diante do fogo de Jacó e José?','dificil','Restolho, que será consumido','Ouro puro','Uma torre inabalável','Um rio caudaloso','A','Obadias 18 descreve a casa de Jacó como fogo e a de Esaú como restolho, que será totalmente consumido.','É um material seco e facilmente inflamável.','texto_biblico',40),
('jonas','Jonas',1,'Para onde Jonas tentou fugir em vez de ir a Nínive?','facil','Társis','Babilônia','Damasco','Jerusalém','A','Jonas 1:3 relata que o profeta embarcou em um navio rumo a Társis, fugindo da presença do Senhor.','Era uma cidade distante, na direção oposta a Nínive.','texto_biblico',46),
('jonas','Jonas',1,'Como os marinheiros descobriram que Jonas era o responsável pela tempestade?','facil','Lançaram sortes','Um anjo apareceu','Jonas confessou espontaneamente logo no início','Consultaram um oráculo egípcio','A','Jonas 1:7 relata que os marinheiros lançaram sortes, e a sorte caiu sobre Jonas.','É um método antigo de decisão por acaso.','texto_biblico',47),
('jonas','Jonas',2,'O que Jonas declara sobre a salvação em sua oração de dentro do peixe (Jonas 2:9)?','medio','A salvação pertence ao Senhor','A salvação vem dos sacerdotes','A salvação depende dos marinheiros','Não há salvação possível','A','Jonas 2:9 conclui a oração afirmando que a salvação pertence ao Senhor.','É a frase de encerramento da oração no ventre do peixe.','texto_biblico',48),
('jonas','Jonas',3,'Qual foi a mensagem exata que Jonas pregou em Nínive, segundo Jonas 3:4?','medio','Ainda quarenta dias, e Nínive será destruída','Nínive será poupada para sempre','Israel será restaurado em breve','Os reis da terra se converterão','A','Jonas 3:4 registra o anúncio de julgamento em quarenta dias sobre Nínive.','Envolve um prazo específico de dias.','texto_biblico',49),
('jonas','Jonas',4,'No argumento final de Deus a Jonas, quantas pessoas incapazes de discernir a mão direita da esquerda havia em Nínive?','dificil','Mais de cento e vinte mil','Exatamente cem','Doze mil','Um milhão','A','Jonas 4:11 menciona mais de cento e vinte mil pessoas em Nínive, além de muitos animais, como razão da compaixão de Deus.','É um número alto, citado junto com os animais da cidade.','texto_biblico',50),
('miqueias','Miquéias',2,'Contra quem é pronunciado o "ai" em Miquéias 2:1?','facil','Os que maquinam a iniquidade em suas camas','Os pastores fiéis','Os estrangeiros pobres','As crianças de Judá','A','Miquéias 2:1 denuncia os que planejam o mal durante a noite e o praticam pela manhã.','O planejamento do mal ocorre à noite.','texto_biblico',56),
('miqueias','Miquéias',7,'O que Miquéias declara em 7:8 mesmo depois de cair?','facil','Levantar-me-ei','Desistirei','Fugirei para sempre','Esconder-me-ei','A','Miquéias 7:8 expressa confiança: ainda que eu caia, levantar-me-ei.','É uma declaração de esperança e confiança.','texto_biblico',57),
('miqueias','Miquéias',7,'Segundo Miquéias 7:19, o que Deus faz com os pecados do seu povo?','medio','Lança-os nas profundezas do mar','Guarda-os para sempre','Reparte-os entre as nações','Transforma-os em ouro','A','Miquéias 7:19 descreve o perdão de Deus como lançar os pecados nas profundezas do mar.','É uma imagem de perdão completo e definitivo.','texto_biblico',58),
('miqueias','Miquéias',3,'Em contraste com falsos profetas, do que Miquéias 3:8 diz estar cheio?','medio','Do poder do Espírito do Senhor','De riquezas materiais','De exércitos','De sabedoria humana apenas','A','Miquéias 3:8 afirma que o profeta está cheio do poder do Espírito do Senhor, de juízo e de força para denunciar o pecado.','É uma afirmação de autoridade profética genuína.','texto_biblico',59),
('miqueias','Miquéias',1,'Durante o reinado de quais reis de Judá Miquéias profetizou, segundo Miquéias 1:1?','dificil','Jotão, Acaz e Ezequias','Saul, Davi e Salomão','Nabucodonosor e Ciro','Herodes e Augusto','A','Miquéias 1:1 situa o ministério do profeta nos dias de Jotão, Acaz e Ezequias, reis de Judá.','São três reis de Judá do período pré-exílico.','texto_biblico',60),
('naum','Naum',1,'Como Naum 1:7 descreve o Senhor para os que confiam nele?','facil','Bom e fortaleza no dia da angústia','Distante e indiferente','Fraco diante dos inimigos','Ausente em tempos de crise','A','Naum 1:7 afirma que o Senhor é bom, fortaleza no dia da angústia, e conhece os que nele confiam.','É um verso de consolo em meio ao anúncio de juízo.','texto_biblico',66),
('naum','Naum',1,'O que Naum 1:15 anuncia que chega sobre os montes?','facil','Os pés do que anuncia a paz','Um novo exército assírio','Uma nuvem de gafanhotos','Uma seca prolongada','A','Naum 1:15 anuncia os pés do mensageiro de boas novas, que proclama a paz após a queda de Nínive.','É uma imagem semelhante à de Isaías 52:7.','texto_biblico',67),
('naum','Naum',3,'A que Nínive é comparada em Naum 3:4 por causa de suas seduções?','medio','Uma prostituta encantadora e mestra de feitiços','Uma noiva fiel','Uma cidade santa','Uma mãe protetora','A','Naum 3:4 acusa Nínive de seduzir nações como uma prostituta encantadora, mestra de feitiçarias.','A acusação envolve sedução e engano.','texto_biblico',68),
('naum','Naum',2,'A que Nínive é comparada em Naum 2:11-12, por causa de sua violência conquistadora?','medio','Um covil de leões','Um jardim florido','Uma torre pacífica','Um templo sagrado','A','Naum 2:11-12 compara Nínive a um covil de leões, cheio de presas, símbolo de sua violência contra outras nações.','É uma comparação com um animal predador feroz.','texto_biblico',69),
('naum','Naum',1,'O que Deus decreta contra a descendência do rei assírio em Naum 1:14?','dificil','Que seu nome não teria mais descendência','Que seria coroado rei universal','Que reconstruiria o templo de Jerusalém','Que se tornaria aliado de Judá','A','Naum 1:14 anuncia que do nome do rei assírio não haveria mais semeadura, e os ídolos de sua casa seriam destruídos.','Envolve o fim da linhagem e dos ídolos do rei.','texto_biblico',70),
('habacuque','Habacuque',1,'Como começa o lamento de Habacuque no capítulo 1?','facil','Até quando, Senhor, clamarei e tu não ouvirás?','Louvado seja o Senhor para sempre','Eis que o rei chegou vitorioso','O templo está reconstruído','A','Habacuque 1:2 abre o livro com uma queixa sobre a violência e a aparente demora da resposta de Deus.','É uma pergunta sobre o tempo de espera.','texto_biblico',76),
('habacuque','Habacuque',3,'Com que imagem de força Habacuque 3:19 termina o livro?','facil','Pés como os das cervas, andando nas alturas','Um exército invencível','Um novo templo de ouro','Uma frota poderosa','A','Habacuque 3:19 declara que o Senhor é sua força e faz seus pés como os da cerva, capazes de andar sobre as alturas.','É uma comparação com um animal ágil em terrenos altos.','texto_biblico',77),
('habacuque','Habacuque',2,'O que Habacuque 2:14 promete que encherá a terra?','medio','O conhecimento da glória do Senhor','O ouro das nações','Os exércitos da Babilônia','As águas do dilúvio','A','Habacuque 2:14 promete que a terra se encherá do conhecimento da glória do Senhor, como as águas cobrem o mar.','É uma imagem de plenitude comparada à água do mar.','texto_biblico',78),
('habacuque','Habacuque',2,'Quantos "ais" (pronunciamentos de juízo) Habacuque declara contra o opressor no capítulo 2?','medio','Cinco','Dois','Dez','Nenhum','A','Habacuque 2:6-19 registra cinco declarações de "ai" contra a injustiça e a opressão do conquistador.','É uma série de acusações repetidas com a mesma palavra.','texto_biblico',79),
('habacuque','Habacuque',1,'Na segunda queixa de Habacuque (cap. 1), o que o incomoda sobre o uso dos caldeus por Deus?','dificil','Que Deus use um povo mais ímpio para julgar um povo menos ímpio','Que os caldeus sejam pobres','Que os caldeus adorem o Deus de Israel','Que os caldeus nunca vençam guerras','A','Habacuque 1:12-13 questiona como Deus, de olhos puros, pode usar os caldeus, mais perversos, para punir um povo menos ímpio.','É um questionamento sobre a justiça divina usando um instrumento moralmente pior.','texto_biblico',80),
('sofonias','Sofonias',1,'Qual é a extensão do juízo anunciado logo no início de Sofonias 1:2-3?','facil','Destruição total sobre homens, animais, aves e peixes','Apenas sobre os sacerdotes','Somente sobre a Assíria','Apenas sobre os estrangeiros','A','Sofonias 1:2-3 anuncia uma destruição abrangente sobre toda a face da terra, incluindo homens e animais.','É uma linguagem de juízo cósmico e abrangente.','texto_biblico',86),
('sofonias','Sofonias',3,'O que o Senhor faz por seu povo com alegria, segundo Sofonias 3:17?','facil','Canta sobre eles com júbilo','Os abandona no deserto','Os envia ao exílio','Os pune sem misericórdia','A','Sofonias 3:17 descreve Deus se alegrando e cantando sobre seu povo com júbilo, uma imagem terna do amor divino.','É uma imagem de alegria e canto de Deus.','texto_biblico',87),
('sofonias','Sofonias',1,'Com o que Sofonias 1:12 compara os que estavam acomodados espiritualmente?','medio','Vinho parado sobre as fezes (borra)','Ouro refinado','Água corrente e pura','Pão fresco','A','Sofonias 1:12 fala de buscar com lanternas os que estão acomodados como vinho sobre a borra, indiferentes ao Senhor.','É uma imagem de estagnação e indiferença espiritual.','texto_biblico',88),
('sofonias','Sofonias',2,'Quais grupos de nações são alvo dos oráculos de juízo em Sofonias 2?','medio','Filístia, Moabe, Amom, Cuxe e Assíria','Apenas Roma e Grécia','Somente as tribos de Israel','Apenas o Egito','A','Sofonias 2 traz oráculos de juízo contra Filístia, Moabe, Amom, Cuxe (Etiópia) e a Assíria.','São nações vizinhas de Judá, incluindo a grande potência assíria.','texto_biblico',89),
('sofonias','Sofonias',1,'Segundo a genealogia em Sofonias 1:1, o profeta é apresentado como descendente de qual rei de Judá?','dificil','Ezequias','Davi','Salomão','Josias, seu contemporâneo','A','Sofonias 1:1 traça a genealogia do profeta até Ezequias, sugerindo possível ascendência real.','É um rei reformador anterior a Josias.','texto_biblico',90),
('ageu','Ageu',1,'O que Ageu 1:6 diz sobre o salário de quem trabalhava enquanto negligenciava o templo?','facil','Era posto num saco furado','Dobrava a cada semana','Era guardado com segurança','Vinha do Egito','A','Ageu 1:6 descreve a futilidade econômica do povo, comparando o salário a algo posto num saco furado.','É uma imagem de perda constante e frustração.','texto_biblico',96),
('ageu','Ageu',1,'O que Deus declarou ao povo depois que eles obedeceram e começaram a reconstrução, segundo Ageu 1:13?','facil','Eu sou convosco','Eu vos abandono','Não voltarei mais','Esquecerei o templo','A','Ageu 1:13 registra a palavra de encorajamento do Senhor: Eu sou convosco, diz o Senhor.','É uma promessa de presença divina.','texto_biblico',97),
('ageu','Ageu',2,'O que Ageu 2:7 anuncia que virá depois que Deus abalar céus e terra?','medio','O Desejado de todas as nações','Um novo dilúvio','A queda definitiva de Jerusalém','O fim dos sacrifícios','A','Ageu 2:6-7 anuncia o abalo dos céus e da terra, seguido da vinda do Desejado de todas as nações, enchendo a casa de glória.','É uma expressão messiânica sobre expectativa das nações.','texto_biblico',98),
('ageu','Ageu',1,'Segundo Ageu 1:14, o que o Senhor despertou em Zorobabel, Josué e no povo?','medio','O espírito para trabalharem na casa do Senhor','O desejo de fugir para o Egito','A vontade de abandonar Judá','O interesse em construir palácios pessoais','A','Ageu 1:14 relata que o Senhor despertou o espírito de Zorobabel, Josué e do restante do povo para a obra da reconstrução.','É um despertar coletivo para o trabalho no templo.','texto_biblico',99),
('ageu','Ageu',2,'No versículo final de Ageu (2:23), a que objeto de honra Deus compara Zorobabel?','dificil','Um anel de selar','Uma coroa de ouro','Uma espada real','Um cetro de ferro','A','Ageu 2:23 declara que Deus fará de Zorobabel, seu servo, como um anel de selar, símbolo de honra e escolha divina.','É um objeto usado para autenticar documentos com um selo pessoal.','texto_biblico',100),
('zacarias','Zacarias',3,'Na visão de Zacarias 3, quem acusa o sumo sacerdote Josué diante do anjo do Senhor?','facil','Satanás','Um sacerdote rival','O rei da Babilônia','Um profeta falso','A','Zacarias 3:1 descreve Satanás à direita de Josué, o sumo sacerdote, para acusá-lo, mas o Senhor o repreende.','É o acusador por excelência nas Escrituras.','texto_biblico',106),
('zacarias','Zacarias',6,'O que Zacarias vê saindo dentre dois montes de bronze na visão do capítulo 6?','facil','Quatro carros puxados por cavalos','Um exército de anjos armados','Uma frota de navios','Uma nuvem de fogo apenas','A','Zacarias 6:1-8 descreve quatro carros com cavalos de cores diferentes, representando os quatro espíritos dos céus.','São veículos puxados por cavalos de cores distintas.','texto_biblico',107),
('zacarias','Zacarias',8,'Segundo Zacarias 8:23, o que dez homens de todas as línguas farão a um judeu?','medio','Tomarão pela orla de sua veste, dizendo que irão com ele','Expulsarão da cidade','Pedirão para adorar outros deuses','Ignorarão completamente','A','Zacarias 8:23 anuncia que nações desejarão acompanhar o povo judeu, pois reconhecerão que Deus está com eles.','Envolve reconhecimento da presença de Deus com o povo.','texto_biblico',108),
('zacarias','Zacarias',11,'Por quantas moedas de prata o pastor (representando o Senhor) foi avaliado em Zacarias 11:12?','medio','Trinta','Dez','Cem','Mil','A','Zacarias 11:12-13 menciona trinta moedas de prata, valor depois associado à traição de Judas contra Jesus.','É o mesmo valor pago pela traição de Judas no Novo Testamento.','texto_biblico',109),
('zacarias','Zacarias',14,'Em Zacarias 14:4, onde os pés do Senhor se firmarão, fazendo o monte se fender em duas partes?','dificil','Monte das Oliveiras','Monte Carmelo','Monte Sinai','Monte Nebo','A','Zacarias 14:4 descreve os pés do Senhor firmados no monte das Oliveiras, que se fenderá ao meio no dia do Senhor.','É o monte a leste de Jerusalém.','texto_biblico',110),
('malaquias','Malaquias',1,'Que tipo de animais o povo oferecia indevidamente em sacrifício, segundo Malaquias 1:8?','facil','Cegos, coxos e enfermos','Somente animais gordos e perfeitos','Apenas aves selvagens','Peixes do rio Jordão','A','Malaquias 1:8 repreende o povo por oferecer animais cegos, coxos e enfermos, desonrando a Deus.','São animais com defeitos físicos.','texto_biblico',116),
('malaquias','Malaquias',2,'O que Malaquias 2:16 diz que o Senhor aborrece?','facil','O repúdio (divórcio)','Os dízimos','As orações longas','Os sacrifícios de louvor','A','Malaquias 2:16 declara que o Senhor Deus de Israel aborrece o repúdio, condenando a infidelidade conjugal.','É relacionado à quebra do casamento.','texto_biblico',117),
('malaquias','Malaquias',3,'O que Malaquias 3:6 afirma sobre o caráter de Deus que garante que Israel não foi consumido?','medio','Eu, o Senhor, não mudo','Eu esqueço facilmente','Eu mudo conforme as nações','Eu abandono meu povo','A','Malaquias 3:6 afirma a imutabilidade de Deus como razão pela qual os filhos de Jacó não foram consumidos.','É uma afirmação sobre a constância do caráter divino.','texto_biblico',118),
('malaquias','Malaquias',3,'De que forma Malaquias 3:8 diz que o povo estava roubando a Deus?','medio','Nos dízimos e nas ofertas','Nos sacrifícios de animais','Na construção do templo','Nas orações públicas','A','Malaquias 3:8 acusa o povo de roubar a Deus retendo dízimos e ofertas.','Está ligado à contribuição financeira ao templo.','texto_biblico',119),
('malaquias','Malaquias',2,'Qual argumento de unidade Malaquias 2:10 usa para repreender a traição entre irmãos?','dificil','Não temos todos um mesmo Pai e um mesmo Criador?','Não somos todos reis?','Não vivemos todos no Egito?','Não somos todos sacerdotes?','A','Malaquias 2:10 apela à paternidade comum de Deus para denunciar a deslealdade entre os israelitas, quebrando a aliança dos pais.','É um apelo à origem e criação comuns.','texto_biblico',120)
) as v(book,book_name,chapter,question,difficulty,option_a,option_b,option_c,option_d,correct_answer,explanation,hint,source_type,order_index)
where not exists (
  select 1 from public.questions q
  where q.book = v.book and q.question = v.question
);

-- Verificação rápida (opcional): deve retornar 10 para cada um dos 12 livros.
-- select book, count(*) from public.questions group by book order by book;
